(function(){
'use strict';function l(a){return{x:a.x,y:a.y}}function B(a,d){return{x:a.x*d,y:a.y*d}}function C(a,d){return{x:~~(a.x/d),y:~~(a.y/d)}}
!function(a){a.StateMachine=class{constructor(){this._stateDictionary={};this._stateStack=[]}register(a){this._stateDictionary[a.name]=a}get current(){return this._stateStack[this._stateStack.length-1]}push(a){this.current&&this.current.transitionOut&&this.current.transitionOut();this._stateStack.push(this._stateDictionary[a]);this.current&&this.current.transitionIn&&this.current.transitionIn()}pop(){this.current&&this.current.transitionOut&&this.current.transitionOut();var a=this._stateStack.pop();
return this.current&&this.current.transitionIn&&this.current.transitionIn(),a}}}(E||(E={}));
(function(a){!function(a){function c(a,b,c){c=a.createShader(c);return a.shaderSource(c,b),a.compileShader(c),c}function e(a,b,f){var g=a.createProgram();b=c(a,b,35633);f=c(a,f,35632);return a.attachShader(g,b),a.attachShader(g,f),a.linkProgram(g),g}function f(a,b,c,f){var g=a.createBuffer();return a.bindBuffer(b,g),a.bufferData(b,c,f),g}a.CompileShader=c;a.CreateShaderProgram=e;a.CreateBuffer=f;a.CreateTexture=function(a,b){var c=a.createTexture();return a.bindTexture(3553,c),a.texParameteri(3553,
10242,33071),a.texParameteri(3553,10243,33071),a.texParameteri(3553,10240,9728),a.texParameteri(3553,10241,9728),a.texImage2D(3553,0,6408,6408,5121,b),a.bindTexture(3553,null),c};a.Renderer=function(a){var b=a.getContext("webgl"),c=a.width,g=a.height,d=e(b,"precision lowp float;\nattribute vec2 a, b;\nattribute vec4 c;\nvarying vec2 d;\nvarying vec4 e;\nuniform mat4 m;\nuniform vec2 r;\nvoid main(){\ngl_Position\x3dm*vec4(a,1.0,1.0);\nd\x3db;\ne\x3dc;\n}","precision lowp float;\nvarying vec2 d;\nvarying vec4 e;\nuniform sampler2D f;\nvoid main(){\ngl_FragColor\x3dtexture2D(f,d)*e;\n}"),
n=b.bufferSubData.bind(b),z=b.drawElements.bind(b),O=b.bindTexture.bind(b),G=b.clear.bind(b),A=b.clearColor.bind(b),D=new ArrayBuffer(873760),r=new Float32Array(D),H=new Uint32Array(D);var u=new Uint16Array(131064);var q=f(b,34963,u.byteLength,35044);var y=f(b,34962,D.byteLength,35048);var w=0,k=new Float32Array([1,0,0,1,0,0]),t=new Float32Array(100),p=0,P=Math.cos,Q=Math.sin,J=null;b.blendFunc(770,771);b.enable(3042);b.useProgram(d);b.bindBuffer(34963,q);for(var v=q=0;65532>q;q+=6,v+=4)u[q+0]=v,
u[q+1]=v+1,u[q+2]=v+2,u[q+3]=v+0,u[q+4]=v+3,u[q+5]=v+1;n(34963,0,u);b.bindBuffer(34962,y);u=b.getAttribLocation(d,"a");y=b.getAttribLocation(d,"b");q=b.getAttribLocation(d,"c");b.enableVertexAttribArray(u);b.vertexAttribPointer(u,2,5126,!1,20,0);b.enableVertexAttribArray(y);b.vertexAttribPointer(y,2,5126,!1,20,8);b.enableVertexAttribArray(q);b.vertexAttribPointer(q,4,5121,!0,20,16);b.uniformMatrix4fv(b.getUniformLocation(d,"m"),!1,new Float32Array([2/c,0,0,0,0,-2/g,0,0,0,0,1,1,-1,1,0,0]));b.activeTexture(33984);
let L={gl:b,canvas:a,col:4294967295,bkg:function(a,b,c){A(a,b,c,1)},cls:function(){G(16384)},trans:function(a,b){k[4]=k[0]*a+k[2]*b+k[4];k[5]=k[1]*a+k[3]*b+k[5]},scale:function(a,b){k[0]*=a;k[1]*=a;k[2]*=b;k[3]*=b},rot:function(a){var b=k[0],c=k[1],f=k[2],d=k[3],e=Q(a);a=P(a);k[0]=b*a+f*e;k[1]=c*a+d*e;k[2]=b*-e+f*a;k[3]=c*-e+d*a},push:function(){t[p+0]=k[0];t[p+1]=k[1];t[p+2]=k[2];t[p+3]=k[3];t[p+4]=k[4];t[p+5]=k[5];p+=6},pop:function(){p-=6;k[0]=t[p+0];k[1]=t[p+1];k[2]=t[p+2];k[3]=t[p+3];k[4]=t[p+
4];k[5]=t[p+5]},img:function(a,b,c,f,d,e,g,h,m){var x=b+f,G=c+d;d=c+d;f=b+f;var A=k[0],p=k[1],q=k[2],t=k[3],u=k[4],v=k[5],y=L.col;(a!=J||10922<=w+1)&&(n(34962,0,D),z(4,6*w,5123,0),w=0,J!=a&&O(3553,J=a));a=20*w;r[a++]=b*A+c*q+u;r[a++]=b*p+c*t+v;r[a++]=e;r[a++]=g;H[a++]=y;r[a++]=x*A+G*q+u;r[a++]=x*p+G*t+v;r[a++]=h;r[a++]=m;H[a++]=y;r[a++]=b*A+d*q+u;r[a++]=b*p+d*t+v;r[a++]=e;r[a++]=m;H[a++]=y;r[a++]=f*A+c*q+u;r[a++]=f*p+c*t+v;r[a++]=h;r[a++]=g;H[a++]=y;10922<=++w&&(n(34962,0,D),z(4,6*w,5123,0),w=0)},
flush:function(){0!=w&&(n(34962,0,r.subarray(0,20*w)),z(4,6*w,5123,0),w=0)}};return L}}(a.GL||(a.GL={}))})(E||(E={}));
(function(a){!function(d){function c(a){let b=a-g;g=a;(function(a,b){let c=f.current;c&&c.update(a,b)})(a,b);(function(a,b){let c=f.current;d._gl.cls();c&&c.render(d._gl,a,b);d._gl.flush()})(a,b);requestAnimationFrame(c)}let e,f,g;d.WIDTH=0;d.HEIGHT=0;d.addScene=function(a){f.register(a)};d.pushScene=function(a){f.push(a)};d.popScene=function(){f.pop()};d.init=function(b){e=b;d._gl=a.GL.Renderer(e);f=new a.StateMachine;d.WIDTH=d._gl.canvas.width;d.HEIGHT=d._gl.canvas.height};d.start=function(){g=
performance.now();d._gl.bkg(25,25,25);requestAnimationFrame(c)}}(a.Core||(a.Core={}))})(E||(E={}));
(function(a){!function(d){d.TextureAtlasStore={};d.TextureStore={};d.load=function(c,e){let f=0,g=()=>{0>=--f&&e()};for(let b in c){let e=new Image;e.onload=function(b,f,e){let g=c[b];return()=>{let c=a.GL.CreateTexture(a.Core._gl.gl,f,f.width,f.height),h=g.textures;d.TextureAtlasStore[b]=c;for(let a=0;a<h.length;a++)for(let b=0;b<h[a].length;b++)d.TextureStore[h[a][b]]={atlas:c,w:g.sWidth,h:g.sHeight,u0:b*g.sWidth/f.width,v0:a*g.sHeight/f.height,u1:(b*g.sWidth+g.sWidth)/f.width,v1:(a*g.sHeight+g.sHeight)/
f.height};e()}}(b,e,g);f++;e.src=c[b].loc}}}(a.Assets||(a.Assets={}))})(E||(E={}));
(function(a){!function(a){function c(a){a=a.which;g[a]&&f[a]&&f[a].keyDown();g[a]=!1}function e(a){a=a.which;f[a]&&f[a].keyUp();g[a]=!0}a.Controls={};let f=[],g=[];for(let a=0;256>a;a++)g[a]=!0;window.onkeydown=c;window.onkeyup=e;a.keyDown=c;a.keyUp=e;a.bindKey=function(a,c,e=()=>{}){f[a]={keyDown:c,keyUp:e}};a.unbindKey=function(a){delete f[a]};a.bindControl=function(b,c,e=()=>{}){for(let g of a.Controls[b])f[g]={keyDown:c,keyUp:e}};a.unbindControl=function(b){for(let c of a.Controls[b])delete f[c]}}(a.Input||
(a.Input={}))})(E||(E={}));
const F={linear:function(a){return a},inQuad:function(a){return a*a},outQuad:function(a){return a*(2-a)},inOutQuad:function(a){return.5>a?2*a*a:(4-2*a)*a-1},inCubic:function(a){return a*a*a},outCubic:function(a){return--a*a*a+1},inOutCubic:function(a){return.5>a?4*a*a*a:(a-1)*(2*a-2)*(2*a-2)+1},inQuart:function(a){return a*a*a*a},outQuart:function(a){return 1- --a*a*a*a},inOutQuart:function(a){return.5>a?8*a*a*a*a:1-8*--a*a*a*a},inQuint:function(a){return a*a*a*a*a},outQuint:function(a){return 1+--a*
a*a*a*a},inOutQuint:function(a){return.5>a?16*a*a*a*a*a:1+16*--a*a*a*a*a}};function*I(a,d,c){let e;for(e=yield 0;e-a<d;)e=yield c((e-a)/d);if(e-a>=d)return 1}var E,K,M,N;
!function(a){a.TileStorage={};a.TileNames={};(function(d){let c;!function(a){a.draw=function(a,c,b,e,x){d.Texture.draw(a,b,e*b.w-c.position.x,x*b.h-c.position.y)}}(c=d.Tile||(d.Tile={}));(function(e){e.draw=function(f,e,b){let g=C(e.position,b.tileSize),d=C(e.size,b.tileSize);for(let h=g.x;h<d.x;h++)for(let n=g.y;n<d.y;n++){let g=a.TileMap.getTile(b,{x:h,y:n});null!=g&&(f.col=g.colour,c.draw(f,e,g.texture,h,n))}}})(d.TileMap||(d.TileMap={}))})(a.Graphics||(a.Graphics={}));(function(d){function c(){return e.next().value}
let e=function*(){let a=0;for(;;)yield a++}();d.NextTileId=c;d.CreateAndStore=function(f,e,b,d){e={id:c(),texture:e,colour:b,hasCollision:d};return a.TileStorage[f]=e,a.TileNames[e.id]=f,e}})(a.Tile||(a.Tile={}));(function(d){d.addTile=function(a,e,f){f=f.x+f.y*a.mapSize.x;void 0===a.tiles[f]&&(a.tiles[f]=0);a.tiles[f]|=e.hasCollision?1:0;a.tiles[f]|=e.id<<1};d.getTile=function(c,e){return a.TileStorage[a.TileNames[c.tiles[e.x+e.y*c.mapSize.x]>>1]]}})(a.TileMap||(a.TileMap={}))}(E||(E={}));
(function(a){!function(a){function c(a,c){c=a.interpolator.next(c);let f=a.origin,b=a.target;a.position.x=f.x+Math.round((b.x-f.x)*c.value);a.position.y=f.y+Math.round((b.y-f.y)*c.value);1==c.done&&(a.moving=!1,a.position=l(a.target),a.origin=l(a.target),a.interpolator=null)}a.create=function(a,c){return{position:a,origin:a,target:a,size:c,moving:!1,interpolator:null}};a.update=function(a,f){a.moving&&c(a,f)};a.move=function(a,c,g,b=0,d=(a)=>a){a.target=l(c);0>a.target.x&&(a.target.x=0);0>a.target.y&&
(a.target.y=0);a.origin=l(a.position);a.interpolator=I(g,b,d);a.moving=!0};a.interpolate=c}(a.Camera||(a.Camera={}))})(E||(E={}));
(function(a){!function(d){d.SpriteStore={};d.NinePatchStore={};class c{constructor(a){this.animations={};this.animationQueue=[];this.animations.DEFAULT=a;this.play("DEFAULT")}get currentAnimation(){return this.animationQueue[0]}get currentFrame(){return this.currentAnimation.currentFrame}addAnimation(a,c){this.animations[a]=c}play(a,c=!1){return this.animationQueue.length=0,this.animations[a].loop=c,this.animationQueue.push(this.animations[a]),this}then(a,c=!1){return this.animations[a].loop=c,this.animationQueue.push(this.animations[a]),
this}next(){this.animationQueue.shift();0===this.animationQueue.length&&this.stop()}stop(){this.animationQueue.length=0;this.animationQueue.push(this.animations.DEFAULT)}update(a,c){this.currentAnimation.done&&this.next();this.currentAnimation.update(c)}}let e;d.Sprite=c;(function(c){c.Animation=class{constructor(a){this._duration=-1;this.progress=0;this.done=this.loop=!1;this.frames=a}get currentFrame(){if(0===this.duration)return this.frames[0];{let a=0;for(let b in this.frames)if(a+=this.frames[b].duration,
this.progress<=a)return this.frames[b];return this.frames[this.frames.length-1]}}get duration(){if(-1===this._duration){this._duration=0;for(let a of this.frames)this._duration+=a.duration}return this._duration}update(a){if(this.done=!1,0===this.duration)return this.frames[0];this.progress+=a;this.progress>this.duration&&(this.loop?this.progress=0:(this.progress=0,this.done=!0))}};c.CreateAndStore=function(f){let b=new c(new c.Animation([{texture:a.Assets.TextureStore[f.animations.DEFAULT[0].texture],
duration:f.animations.DEFAULT[0].duration}]));for(let d in f.animations){let e=f.animations[d],g=[];for(let b of e)g.push({texture:a.Assets.TextureStore[b.texture],duration:b.duration});b.addAnimation(d,new c.Animation(g))}return d.SpriteStore[f.name]=b,b}})(c=d.Sprite||(d.Sprite={}));(function(a){a.draw=function(a,b,c,f,d,n){d=c+d-1;let g=f+n-1;for(let h=c;h<=d;h++)for(let m=f;m<=g;m++)n=h===c?m===f?b.tl:m===g?b.bl:b.ml:h===d?m===f?b.tr:m===g?b.br:b.mr:m===f?b.tc:m===g?b.bc:b.mc,e.draw(a,n,h*n.w,
m*n.h)}})(d.NinePatch||(d.NinePatch={}));(function(a){a.draw=function(a,b,c,f,d=!0){let e=b.w,g=d?~~(b.w/2):0,h=b.h;d=d?~~(b.h/2):0;a.push();a.trans(c+g,f+d);a.img(b.atlas,-g,-d,e,h,b.u0,b.v0,b.u1,b.v1);a.pop()}})(e=d.Texture||(d.Texture={}));(function(c){let d;!function(a){a[a.LEFT=0]="LEFT";a[a.CENTER=1]="CENTER";a[a.RIGHT=2]="RIGHT"}(d=c.Alignment||(c.Alignment={}));c.draw=function(c,f,e,g,n=d.LEFT,z=0){let b=f.split(" "),h=e,m=0;e=0==z?6*f.split("").length:z;f=0;n==d.CENTER?f=~~(-e/2):n===d.RIGHT&&
(f=~~-e);for(let d of b){0!=z&&m+6*d.length>z&&(g+=6,m=0);for(let b of d.split(""))e=b.toLowerCase(),n=a.Assets.TextureStore[e],e=h+m,c.push(),c.trans(e,g),c.img(n.atlas,f,0,n.w,n.h,n.u0,n.v0,n.u1,n.v1),c.pop(),m+=6;m+=6}}})(d.Text||(d.Text={}))}(a.Graphics||(a.Graphics={}))})(E||(E={}));
(function(a){var d=E,c=d.Core,e=d.Input,f=d.Graphics,g=d.Assets;let b=0;a.MainMenu={name:"MainMenu",transitionIn(){e.bindControl("DOWN",()=>{2<(b+=1)&&(b=0)});e.bindControl("UP",()=>{0>--b&&(b=2)});e.bindControl("ACTION",()=>{c.pushScene("Main")})},transitionOut(){e.unbindControl("DOWN");e.unbindControl("UP");e.unbindControl("ACTION")},update(){},render(a){a.col=4278190335;f.NinePatch.draw(a,f.NinePatchStore.dialog,0,0,40,22);a.col=4294967295;let d=~~(c.WIDTH/2),e=~~(c.HEIGHT/2);f.Text.draw(a,"Start",
d-16,e,f.Text.Alignment.LEFT);f.Text.draw(a,"Also Start",d-16,e+16,f.Text.Alignment.LEFT);f.Text.draw(a,"They All Start",d-16,e+32,f.Text.Alignment.LEFT);f.Texture.draw(a,g.TextureStore.guy_stand,d-32,e-2+16*b,!1)}}})(M||(M={}));
(function(a){!function(a){let c;!function(a){a.Collections={};a.Position=class{constructor(a,c,d=!0){this.name=a;this.value=c;this.active=d}};a.Tag=class{constructor(a,c){this.name=a;this.value=c}};a.Flag=class{constructor(a,c){this.name=a;this.value=c}};a.Number=class{constructor(a,c){this.name=a;this.value=c}}}(c=a.Component||(a.Component={}));class d{constructor(){this._components={};this.id=d.__id++}addComponent(a){this._components[a.name]=a;this[a.name]=a;null==c.Collections[a.name]&&(c.Collections[a.name]=
[]);c.Collections[a.name].push(this)}}d.__id=0;a.Entity=d}(a.ECS||(a.ECS={}))})(E||(E={}));
(function(a){let d={};a.handlePlayerInput=function(a){0==a.moving.value&&(a.movingRight.value&&a.targetTile.value.x++,a.movingLeft.value&&a.targetTile.value.x--,a.movingUp.value&&a.targetTile.value.y--,a.movingDown.value&&a.targetTile.value.y++,a.tilePos.value.x==a.targetTile.value.x&&a.tilePos.value.y==a.targetTile.value.y||(a.moving.value=!0))};a.handleCollision=function(a,d){(a.movingRight.value||a.movingLeft.value)&&E.TileMap.getTile(d,{x:a.targetTile.value.x,y:a.tilePos.value.y}).hasCollision&&
(a.movingRight.value=a.movingLeft.value=!1,a.targetTile.value.x=a.tilePos.value.x);(a.movingUp.value||a.movingDown.value)&&E.TileMap.getTile(d,{x:a.tilePos.value.x,y:a.targetTile.value.y}).hasCollision&&(a.movingUp.value=a.movingDown.value=!1,a.targetTile.value.y=a.tilePos.value.y);a.tilePos.value.x===a.targetTile.value.x&&a.tilePos.value.y===a.targetTile.value.y&&(a.moving.value=!1)};a.moveEntity=function(a,e){null==d[a.id]&&(d[a.id]={});null==d[a.id].moveFn&&(d[a.id].moveFn=I(e,200,F.linear));e=
d[a.id].moveFn.next(e);let c=B(a.tilePos.value,8),g=B(a.targetTile.value,8);a.renderPos.value.x=c.x+Math.round((g.x-c.x)*e.value);a.renderPos.value.y=c.y+Math.round((g.y-c.y)*e.value);1==e.done&&(a.moving.value=!1,a.tilePos.value=l(a.targetTile.value),a.renderPos.value=B(a.tilePos.value,8),delete d[a.id].moveFn)}})(K||(K={}));
(function(a){var d=E,c=d.ECS,e=c.Component,f=d.Core,g=d.Input,b=d.Graphics;let h=new c.Entity;[].push(h);h.addComponent(new e.Position("tilePos",{x:5,y:5}));h.addComponent(new e.Position("renderPos",{x:40,y:40}));h.addComponent(new e.Position("targetTile",{x:5,y:5}));h.addComponent(new e.Flag("moving",!1));h.addComponent(new e.Flag("movingLeft",!1));h.addComponent(new e.Flag("movingRight",!1));h.addComponent(new e.Flag("movingUp",!1));h.addComponent(new e.Flag("movingDown",!1));let x={mapSize:{x:40,
y:18},tileSize:8,tiles:[]},m=E.Camera.create({x:0,y:0},{x:320,y:144});a.Main={name:"Main",transitionIn(){g.bindControl("RIGHT",()=>{h.movingRight.value=!0},()=>{h.movingRight.value=!1});g.bindControl("LEFT",()=>{h.movingLeft.value=!0},()=>{h.movingLeft.value=!1});g.bindControl("DOWN",()=>{h.movingDown.value=!0},()=>{h.movingDown.value=!1});g.bindControl("UP",()=>{h.movingUp.value=!0},()=>{h.movingUp.value=!1});g.bindControl("ACTION",()=>{f.popScene()});for(let a=0;40>a;a++)for(let b=0;18>b;b++)39===
a||0===a||17===b?E.TileMap.addTile(x,E.TileStorage.wall,{x:a,y:b}):0===b?E.TileMap.addTile(x,E.TileStorage.north_wall,{x:a,y:b}):E.TileMap.addTile(x,E.TileStorage.floor,{x:a,y:b})},transitionOut(){g.unbindControl("RIGHT");g.unbindControl("LEFT");g.unbindControl("DOWN");g.unbindControl("UP");g.unbindControl("ACTION")},update(a,c){if(b.SpriteStore.dude01.update(a,c),b.SpriteStore.dude02.update(a,c),K.handlePlayerInput(h),1==h.moving.value&&(K.handleCollision(h,x),1==h.moving.value&&K.moveEntity(h,a)),
!m.moving){c=h.renderPos.value.x-(m.position.x+~~(m.size.x/2));let b=h.renderPos.value.y-(m.position.y+~~(m.size.y/2));(32<=c||-32>=c||16<=b||-16>=b)&&E.Camera.move(m,{x:h.renderPos.value.x-~~(m.size.x/2),y:h.renderPos.value.y-~~(m.size.y/2)},a,1500,F.outQuart)}E.Camera.update(m,a)},render(a){a.bkg(0,0,0);b.TileMap.draw(a,m,x);a.col=4294967295;b.Texture.draw(a,b.SpriteStore.dude01.currentFrame.texture,40-m.position.x,72-m.position.y);b.Texture.draw(a,b.SpriteStore.dude02.currentFrame.texture,h.renderPos.value.x-
m.position.x,h.renderPos.value.y-m.position.y);b.Texture.draw(a,b.SpriteStore.dude01.currentFrame.texture,272-m.position.x,72-m.position.y);a.col=4294936712;b.NinePatch.draw(a,b.NinePatchStore.dialog,0,18,40,4);a.col=4294967295;b.Text.draw(a,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu condimentum purus, eu pharetra arcu. Mauris imperdiet consectetur odio sed volutpat.",6,150,b.Text.Alignment.LEFT,308)}}})(M||(M={}));
(function(a){var d=E.Core,c=E.Graphics,e=E.Assets;let f=[{name:"dude01",animations:{DEFAULT:[{texture:"guy_stand",duration:0}],walk:[{texture:"guy_01",duration:250},{texture:"guy_02",duration:250}]}},{name:"dude02",animations:{DEFAULT:[{texture:"guy_stand",duration:0}],walk:[{texture:"guy_stand",duration:250},{texture:"guy_01",duration:250},{texture:"guy_stand",duration:250},{texture:"guy_02",duration:250}]}}];a.setup=function(){d.addScene(M.MainMenu);d.addScene(M.Main);for(let a of f)c.Sprite.CreateAndStore(a);
E.Tile.CreateAndStore("north_wall",e.TextureStore.brick,4281545642,!0);E.Tile.CreateAndStore("wall",e.TextureStore.brick,4278321666,!0);E.Tile.CreateAndStore("floor",e.TextureStore.brick,4279176975,!1);c.SpriteStore.dude01.play("walk",!0);c.SpriteStore.dude02.play("walk",!0);c.NinePatchStore.dialog={tl:e.TextureStore.dialog_tl,tc:e.TextureStore.dialog_t,tr:e.TextureStore.dialog_tr,ml:e.TextureStore.dialog_ml,mc:e.TextureStore.dialog_m,mr:e.TextureStore.dialog_mr,bl:e.TextureStore.dialog_bl,bc:e.TextureStore.dialog_b,
br:e.TextureStore.dialog_br};d.pushScene("MainMenu")}})(N||(N={}));
(function(a){var d=E.Core,c=E.Input,e=E.Assets;let f={alpha:{loc:"res/alpha.png",sWidth:5,sHeight:5,textures:["abcdefghijklmnopqrstuvwxyz".split(""),"1234567890.!?#()-^+\x3d/\\:,'\"".split("")]},tiles:{loc:"res/test.png",sWidth:8,sHeight:8,textures:[["brick","guy_stand","guy_01","guy_02"],["dialog_tl","dialog_t","dialog_tr","blank03"],["dialog_ml","dialog_m","dialog_mr","blank04"],["dialog_bl","dialog_b","dialog_br","blank05"]]}};a.onload=function(){function g(){var a=d._gl.canvas,c=0|Math.min(window.innerWidth/
a.width,window.innerHeight/a.height);c=0>=c?1:c;a=[a.width*c,a.height*c];a=[(window.innerWidth-a[0])/2,(window.innerHeight-a[1])/2];c="translate("+~~a[0]+"px, "+~~a[1]+"px) scale("+~~c+")";a=document.getElementById("stage");a.style.transform=c;a.style.webkitTransform=c}d.init(document.getElementById("canvas"));c.Controls.UP=[38,87];c.Controls.DOWN=[40,83];c.Controls.LEFT=[37,65];c.Controls.RIGHT=[39,68];c.Controls.ACTION=[13,32];e.load(f,()=>{window.onresize=g;g();d.start();a.setup()})}})(N||(N={}));
window.onload=N.onload;
})()