(function(){
'use strict';function m(a){return{x:a.x,y:a.y}}function B(a,e){return{x:a.x*e,y:a.y*e}}function C(a,e){return{x:~~(a.x/e),y:~~(a.y/e)}}
!function(a){a.StateMachine=class{constructor(){this._stateDictionary={};this._stateStack=[]}register(a){this._stateDictionary[a.name]=a}get current(){return this._stateStack[this._stateStack.length-1]}push(a){this.current&&this.current.transitionOut&&this.current.transitionOut();this._stateStack.push(this._stateDictionary[a]);this.current&&this.current.transitionIn&&this.current.transitionIn()}pop(){this.current&&this.current.transitionOut&&this.current.transitionOut();var a=this._stateStack.pop();
return this.current&&this.current.transitionIn&&this.current.transitionIn(),a}}}(E||(E={}));
(function(a){!function(a){function c(a,b,c){c=a.createShader(c);return a.shaderSource(c,b),a.compileShader(c),c}function d(a,b,f){var g=a.createProgram();b=c(a,b,35633);f=c(a,f,35632);return a.attachShader(g,b),a.attachShader(g,f),a.linkProgram(g),g}function f(a,b,c,f){var g=a.createBuffer();return a.bindBuffer(b,g),a.bufferData(b,c,f),g}a.CompileShader=c;a.CreateShaderProgram=d;a.CreateBuffer=f;a.CreateTexture=function(a,b){var c=a.createTexture();return a.bindTexture(3553,c),a.texParameteri(3553,
10242,33071),a.texParameteri(3553,10243,33071),a.texParameteri(3553,10240,9728),a.texParameteri(3553,10241,9728),a.texImage2D(3553,0,6408,6408,5121,b),a.bindTexture(3553,null),c};a.Renderer=function(a){var b=a.getContext("webgl"),c=a.width,e=a.height,g=d(b,"precision lowp float;\nattribute vec2 a, b;\nattribute vec4 c;\nvarying vec2 d;\nvarying vec4 e;\nuniform mat4 m;\nuniform vec2 r;\nvoid main(){\ngl_Position\x3dm*vec4(a,1.0,1.0);\nd\x3db;\ne\x3dc;\n}","precision lowp float;\nvarying vec2 d;\nvarying vec4 e;\nuniform sampler2D f;\nvoid main(){\ngl_FragColor\x3dtexture2D(f,d)*e;\n}"),
k=b.bufferSubData.bind(b),p=b.drawElements.bind(b),O=b.bindTexture.bind(b),G=b.clear.bind(b),A=b.clearColor.bind(b),D=new ArrayBuffer(873760),r=new Float32Array(D),H=new Uint32Array(D);var u=new Uint16Array(131064);var q=f(b,34963,u.byteLength,35044);var y=f(b,34962,D.byteLength,35048);var x=0,l=new Float32Array([1,0,0,1,0,0]),t=new Float32Array(100),n=0,P=Math.cos,Q=Math.sin,J=null;b.blendFunc(770,771);b.enable(3042);b.useProgram(g);b.bindBuffer(34963,q);for(var w=q=0;65532>q;q+=6,w+=4)u[q+0]=w,
u[q+1]=w+1,u[q+2]=w+2,u[q+3]=w+0,u[q+4]=w+3,u[q+5]=w+1;k(34963,0,u);b.bindBuffer(34962,y);u=b.getAttribLocation(g,"a");y=b.getAttribLocation(g,"b");q=b.getAttribLocation(g,"c");b.enableVertexAttribArray(u);b.vertexAttribPointer(u,2,5126,!1,20,0);b.enableVertexAttribArray(y);b.vertexAttribPointer(y,2,5126,!1,20,8);b.enableVertexAttribArray(q);b.vertexAttribPointer(q,4,5121,!0,20,16);b.uniformMatrix4fv(b.getUniformLocation(g,"m"),!1,new Float32Array([2/c,0,0,0,0,-2/e,0,0,0,0,1,1,-1,1,0,0]));b.activeTexture(33984);
let L={gl:b,canvas:a,col:4294967295,bkg:function(a,b,c){A(a,b,c,1)},cls:function(){G(16384)},trans:function(a,b){l[4]=l[0]*a+l[2]*b+l[4];l[5]=l[1]*a+l[3]*b+l[5]},scale:function(a,b){l[0]*=a;l[1]*=a;l[2]*=b;l[3]*=b},rot:function(a){var b=l[0],c=l[1],f=l[2],g=l[3],e=Q(a);a=P(a);l[0]=b*a+f*e;l[1]=c*a+g*e;l[2]=b*-e+f*a;l[3]=c*-e+g*a},push:function(){t[n+0]=l[0];t[n+1]=l[1];t[n+2]=l[2];t[n+3]=l[3];t[n+4]=l[4];t[n+5]=l[5];n+=6},pop:function(){n-=6;l[0]=t[n+0];l[1]=t[n+1];l[2]=t[n+2];l[3]=t[n+3];l[4]=t[n+
4];l[5]=t[n+5]},img:function(a,b,c,f,g,e,d,h,v){var z=b+f,G=c+g;g=c+g;f=b+f;var n=l[0],A=l[1],q=l[2],t=l[3],u=l[4],w=l[5],y=L.col;(a!=J||10922<=x+1)&&(k(34962,0,D),p(4,6*x,5123,0),x=0,J!=a&&O(3553,J=a));a=20*x;r[a++]=b*n+c*q+u;r[a++]=b*A+c*t+w;r[a++]=e;r[a++]=d;H[a++]=y;r[a++]=z*n+G*q+u;r[a++]=z*A+G*t+w;r[a++]=h;r[a++]=v;H[a++]=y;r[a++]=b*n+g*q+u;r[a++]=b*A+g*t+w;r[a++]=e;r[a++]=v;H[a++]=y;r[a++]=f*n+c*q+u;r[a++]=f*A+c*t+w;r[a++]=h;r[a++]=d;H[a++]=y;10922<=++x&&(k(34962,0,D),p(4,6*x,5123,0),x=0)},
flush:function(){0!=x&&(k(34962,0,r.subarray(0,20*x)),p(4,6*x,5123,0),x=0)}};return L}}(a.GL||(a.GL={}))})(E||(E={}));
(function(a){!function(e){function c(a){let b=a-g;g=a;(function(a,b){let c=f.current;c&&c.update(a,b)})(a,b);(function(a,b){let c=f.current;e._gl.cls();c&&c.render(e._gl,a,b);e._gl.flush()})(a,b);requestAnimationFrame(c)}let d,f,g;e.WIDTH=0;e.HEIGHT=0;e.addScene=function(a){f.register(a)};e.pushScene=function(a){f.push(a)};e.popScene=function(){f.pop()};e.init=function(b){d=b;e._gl=a.GL.Renderer(d);f=new a.StateMachine;e.WIDTH=e._gl.canvas.width;e.HEIGHT=e._gl.canvas.height};e.start=function(){g=
performance.now();e._gl.bkg(25,25,25);requestAnimationFrame(c)}}(a.Core||(a.Core={}))})(E||(E={}));
(function(a){!function(e){e.TextureAtlasStore={};e.TextureStore={};e.load=function(c,d){let f=0,g=()=>{0>=--f&&d()};for(let d in c){let h=new Image;var b=c[d];h.onload="sWidth"in b&&"sHeight"in b?function(b,f,g){let d=c[b];return()=>{let c=a.GL.CreateTexture(a.Core._gl.gl,f,f.width,f.height),h=d.textures;e.TextureAtlasStore[b]=c;for(let a=0;a<h.length;a++)for(let b=0;b<h[a].length;b++)e.TextureStore[h[a][b]]={atlas:c,w:d.sWidth,h:d.sHeight,u0:b*d.sWidth/f.width,v0:a*d.sHeight/f.height,u1:(b*d.sWidth+
d.sWidth)/f.width,v1:(a*d.sHeight+d.sHeight)/f.height};g()}}(d,h,g):function(b,f,d){let g=c[b];return()=>{let c=a.GL.CreateTexture(a.Core._gl.gl,f,f.width,f.height),h=g.textures;e.TextureAtlasStore[b]=c;for(let a of h)e.TextureStore[a.name]={atlas:c,w:a.width,h:a.height,u0:a.x/f.width,v0:a.y/f.height,u1:(a.x+a.width)/f.width,v1:(a.y+a.height)/f.height};d()}}(d,h,g);f++;h.src=c[d].loc}}}(a.Assets||(a.Assets={}))})(E||(E={}));
(function(a){!function(a){function c(a){a=a.which;g[a]&&f[a]&&f[a].keyDown();g[a]=!1}function d(a){a=a.which;f[a]&&f[a].keyUp();g[a]=!0}a.Controls={};let f=[],g=[];for(let a=0;256>a;a++)g[a]=!0;window.onkeydown=c;window.onkeyup=d;a.keyDown=c;a.keyUp=d;a.bindKey=function(a,c,d=()=>{}){f[a]={keyDown:c,keyUp:d}};a.unbindKey=function(a){delete f[a]};a.bindControl=function(b,c,d=()=>{}){for(let g of a.Controls[b])f[g]={keyDown:c,keyUp:d}};a.unbindControl=function(b){for(let c of a.Controls[b])delete f[c]}}(a.Input||
(a.Input={}))})(E||(E={}));
const F={linear:function(a){return a},inQuad:function(a){return a*a},outQuad:function(a){return a*(2-a)},inOutQuad:function(a){return.5>a?2*a*a:(4-2*a)*a-1},inCubic:function(a){return a*a*a},outCubic:function(a){return--a*a*a+1},inOutCubic:function(a){return.5>a?4*a*a*a:(a-1)*(2*a-2)*(2*a-2)+1},inQuart:function(a){return a*a*a*a},outQuart:function(a){return 1- --a*a*a*a},inOutQuart:function(a){return.5>a?8*a*a*a*a:1-8*--a*a*a*a},inQuint:function(a){return a*a*a*a*a},outQuint:function(a){return 1+--a*
a*a*a*a},inOutQuint:function(a){return.5>a?16*a*a*a*a*a:1+16*--a*a*a*a*a}};function*I(a,e,c){let d;for(d=yield 0;d-a<e;)d=yield c((d-a)/e);if(d-a>=e)return 1}var E,K,M,N;
!function(a){a.TileStorage={};a.TileNames={};(function(e){let c;!function(a){a.draw=function(a,c,b,d,h){e.Texture.draw(a,b,d*b.w-c.position.x,h*b.h-c.position.y)}}(c=e.Tile||(e.Tile={}));(function(d){d.draw=function(f,d,b){let g=C(d.position,b.tileSize),e=C(d.size,b.tileSize);for(let h=g.x;h<e.x;h++)for(let k=g.y;k<e.y;k++){let g=a.TileMap.getTile(b,{x:h,y:k});null!=g&&(f.col=g.colour,c.draw(f,d,g.texture,h,k))}}})(e.TileMap||(e.TileMap={}))})(a.Graphics||(a.Graphics={}));(function(e){function c(){return d.next().value}
let d=function*(){let a=0;for(;;)yield a++}();e.NextTileId=c;e.CreateAndStore=function(f,d,b,e){d={id:c(),texture:d,colour:b,hasCollision:e};return a.TileStorage[f]=d,a.TileNames[d.id]=f,d}})(a.Tile||(a.Tile={}));(function(e){e.addTile=function(a,d,f){f=f.x+f.y*a.mapSize.x;void 0===a.tiles[f]&&(a.tiles[f]=0);a.tiles[f]|=d.hasCollision?1:0;a.tiles[f]|=d.id<<1};e.getTile=function(c,d){return a.TileStorage[a.TileNames[c.tiles[d.x+d.y*c.mapSize.x]>>1]]}})(a.TileMap||(a.TileMap={}))}(E||(E={}));
(function(a){!function(a){function c(a,c){c=a.interpolator.next(c);let f=a.origin,b=a.target;a.position.x=f.x+Math.round((b.x-f.x)*c.value);a.position.y=f.y+Math.round((b.y-f.y)*c.value);1==c.done&&(a.moving=!1,a.position=m(a.target),a.origin=m(a.target),a.interpolator=null)}a.create=function(a,c){return{position:a,origin:a,target:a,size:c,moving:!1,interpolator:null}};a.update=function(a,f){a.moving&&c(a,f)};a.move=function(a,c,g,b=0,e=(a)=>a){a.target=m(c);0>a.target.x&&(a.target.x=0);0>a.target.y&&
(a.target.y=0);a.origin=m(a.position);a.interpolator=I(g,b,e);a.moving=!0};a.interpolate=c}(a.Camera||(a.Camera={}))})(E||(E={}));
(function(a){!function(e){e.SpriteStore={};e.NinePatchStore={};class c{constructor(a){this.animations={};this.animationQueue=[];this.animations.DEFAULT=a;this.play("DEFAULT")}get currentAnimation(){return this.animationQueue[0]}get currentFrame(){return this.currentAnimation.currentFrame}addAnimation(a,c){this.animations[a]=c}play(a,c=!1){return this.animationQueue.length=0,this.animations[a].loop=c,this.animationQueue.push(this.animations[a]),this}then(a,c=!1){return this.animations[a].loop=c,this.animationQueue.push(this.animations[a]),
this}next(){this.animationQueue.shift();0===this.animationQueue.length&&this.stop()}stop(){this.animationQueue.length=0;this.animationQueue.push(this.animations.DEFAULT)}update(a,c){this.currentAnimation.done&&this.next();this.currentAnimation.update(c)}}let d;e.Sprite=c;(function(c){c.Animation=class{constructor(a){this._duration=-1;this.progress=0;this.done=this.loop=!1;this.frames=a}get currentFrame(){if(0===this.duration)return this.frames[0];{let a=0;for(let b in this.frames)if(a+=this.frames[b].duration,
this.progress<=a)return this.frames[b];return this.frames[this.frames.length-1]}}get duration(){if(-1===this._duration){this._duration=0;for(let a of this.frames)this._duration+=a.duration}return this._duration}update(a){if(this.done=!1,0===this.duration)return this.frames[0];this.progress+=a;this.progress>this.duration&&(this.loop?this.progress=0:(this.progress=0,this.done=!0))}};c.CreateAndStore=function(f){let b=new c(new c.Animation([{texture:a.Assets.TextureStore[f.animations.DEFAULT[0].texture],
duration:f.animations.DEFAULT[0].duration}]));for(let d in f.animations){let e=f.animations[d],g=[];for(let b of e)g.push({texture:a.Assets.TextureStore[b.texture],duration:b.duration});b.addAnimation(d,new c.Animation(g))}return e.SpriteStore[f.name]=b,b}})(c=e.Sprite||(e.Sprite={}));(function(a){a.draw=function(a,b,c,f,e,k){e=c+e-1;let g=f+k-1;for(let h=c;h<=e;h++)for(let p=f;p<=g;p++)k=h===c?p===f?b.tl:p===g?b.bl:b.ml:h===e?p===f?b.tr:p===g?b.br:b.mr:p===f?b.tc:p===g?b.bc:b.mc,d.draw(a,k,h*k.w,
p*k.h)}})(e.NinePatch||(e.NinePatch={}));(function(a){a.draw=function(a,b,c,f,e={x:1,y:1},d=!0){let g=b.w,h=d?~~(b.w/2):0,k=b.h;d=d?~~(b.h/2):0;a.push();a.trans(c+h,f+d);a.scale(e.x,e.y);a.img(b.atlas,-h,-d,g,k,b.u0,b.v0,b.u1,b.v1);a.pop()}})(d=e.Texture||(e.Texture={}));(function(c){let f;!function(a){a[a.LEFT=0]="LEFT";a[a.CENTER=1]="CENTER";a[a.RIGHT=2]="RIGHT"}(f=c.Alignment||(c.Alignment={}));c.draw=function(c,d,e,g,k=f.LEFT,p=0){let b=d.split(" "),h=e,v=0;e=0==p?6*d.split("").length:p;d=0;k==
f.CENTER?d=~~(-e/2):k===f.RIGHT&&(d=~~-e);for(let f of b){0!=p&&v+6*f.length>p&&(g+=6,v=0);for(let b of f.split(""))e=b.toLowerCase(),k=a.Assets.TextureStore[e],e=h+v,c.push(),c.trans(e,g),c.img(k.atlas,d,0,k.w,k.h,k.u0,k.v0,k.u1,k.v1),c.pop(),v+=6;v+=6}}})(e.Text||(e.Text={}))}(a.Graphics||(a.Graphics={}))})(E||(E={}));
(function(a){var e=E,c=e.Core,d=e.Input,f=e.Graphics,g=e.Assets;let b=0;a.MainMenu={name:"MainMenu",transitionIn(){d.bindControl("DOWN",()=>{2<(b+=1)&&(b=0)});d.bindControl("UP",()=>{0>--b&&(b=2)});d.bindControl("ACTION",()=>{c.pushScene("Main")})},transitionOut(){d.unbindControl("DOWN");d.unbindControl("UP");d.unbindControl("ACTION")},update(){},render(a){a.col=4278190335;f.NinePatch.draw(a,f.NinePatchStore.dialog,0,0,40,22);a.col=4294967295;let d=~~(c.WIDTH/2),e=~~(c.HEIGHT/2);f.Text.draw(a,"Start",
d-16,e,f.Text.Alignment.LEFT);f.Text.draw(a,"Also Start",d-16,e+16,f.Text.Alignment.LEFT);f.Text.draw(a,"They All Start",d-16,e+32,f.Text.Alignment.LEFT);f.Texture.draw(a,g.TextureStore.guy_stand,d-32,e-2+16*b,{x:1,y:1},!1)}}})(M||(M={}));
(function(a){!function(a){let c;!function(a){a.Collections={};a.Position=class{constructor(a,c,d=!0){this.name=a;this.value=c;this.active=d}};a.Tag=class{constructor(a,c){this.name=a;this.value=c}};a.Flag=class{constructor(a,c){this.name=a;this.value=c}};a.Number=class{constructor(a,c){this.name=a;this.value=c}}}(c=a.Component||(a.Component={}));class d{constructor(){this._components={};this.id=d.__id++}addComponent(a){this._components[a.name]=a;this[a.name]=a;null==c.Collections[a.name]&&(c.Collections[a.name]=
[]);c.Collections[a.name].push(this)}}d.__id=0;a.Entity=d}(a.ECS||(a.ECS={}))})(E||(E={}));
(function(a){let e={};a.handlePlayerInput=function(a){0==a.moving.value&&(a.movingRight.value&&a.targetTile.value.x++,a.movingLeft.value&&a.targetTile.value.x--,a.movingUp.value&&a.targetTile.value.y--,a.movingDown.value&&a.targetTile.value.y++,a.tilePos.value.x==a.targetTile.value.x&&a.tilePos.value.y==a.targetTile.value.y||(a.moving.value=!0))};a.handleCollision=function(a,d){(a.movingRight.value||a.movingLeft.value)&&E.TileMap.getTile(d,{x:a.targetTile.value.x,y:a.tilePos.value.y}).hasCollision&&
(a.movingRight.value=a.movingLeft.value=!1,a.targetTile.value.x=a.tilePos.value.x);(a.movingUp.value||a.movingDown.value)&&E.TileMap.getTile(d,{x:a.tilePos.value.x,y:a.targetTile.value.y}).hasCollision&&(a.movingUp.value=a.movingDown.value=!1,a.targetTile.value.y=a.tilePos.value.y);a.tilePos.value.x===a.targetTile.value.x&&a.tilePos.value.y===a.targetTile.value.y&&(a.moving.value=!1)};a.moveEntity=function(a,d){null==e[a.id]&&(e[a.id]={});null==e[a.id].moveFn&&(e[a.id].moveFn=I(d,200,F.linear));d=
e[a.id].moveFn.next(d);let c=B(a.tilePos.value,8),g=B(a.targetTile.value,8);a.renderPos.value.x=c.x+Math.round((g.x-c.x)*d.value);a.renderPos.value.y=c.y+Math.round((g.y-c.y)*d.value);1==d.done&&(a.moving.value=!1,a.tilePos.value=m(a.targetTile.value),a.renderPos.value=B(a.tilePos.value,8),delete e[a.id].moveFn)}})(K||(K={}));
(function(a){var e=E,c=e.ECS,d=c.Component,f=e.Core,g=e.Input,b=e.Graphics,v=e.Assets;let h=new c.Entity;[].push(h);h.addComponent(new d.Position("tilePos",{x:5,y:5}));h.addComponent(new d.Position("renderPos",{x:40,y:40}));h.addComponent(new d.Position("targetTile",{x:5,y:5}));h.addComponent(new d.Flag("moving",!1));h.addComponent(new d.Flag("movingLeft",!1));h.addComponent(new d.Flag("movingRight",!1));h.addComponent(new d.Flag("movingUp",!1));h.addComponent(new d.Flag("movingDown",!1));let z={mapSize:{x:40,
y:18},tileSize:8,tiles:[]},k=E.Camera.create({x:0,y:0},{x:320,y:144});a.Main={name:"Main",transitionIn(){g.bindControl("RIGHT",()=>{h.movingRight.value=!0},()=>{h.movingRight.value=!1});g.bindControl("LEFT",()=>{h.movingLeft.value=!0},()=>{h.movingLeft.value=!1});g.bindControl("DOWN",()=>{h.movingDown.value=!0},()=>{h.movingDown.value=!1});g.bindControl("UP",()=>{h.movingUp.value=!0},()=>{h.movingUp.value=!1});g.bindControl("ACTION",()=>{f.popScene()});for(let a=0;40>a;a++)for(let b=0;18>b;b++)39===
a||0===a||17===b?E.TileMap.addTile(z,E.TileStorage.wall,{x:a,y:b}):0===b?E.TileMap.addTile(z,E.TileStorage.north_wall,{x:a,y:b}):E.TileMap.addTile(z,E.TileStorage.floor,{x:a,y:b})},transitionOut(){g.unbindControl("RIGHT");g.unbindControl("LEFT");g.unbindControl("DOWN");g.unbindControl("UP");g.unbindControl("ACTION")},update(a,c){if(b.SpriteStore.dude01.update(a,c),b.SpriteStore.dude02.update(a,c),K.handlePlayerInput(h),1==h.moving.value&&(K.handleCollision(h,z),1==h.moving.value&&K.moveEntity(h,a)),
!k.moving){c=h.renderPos.value.x-(k.position.x+~~(k.size.x/2));let b=h.renderPos.value.y-(k.position.y+~~(k.size.y/2));(32<=c||-32>=c||16<=b||-16>=b)&&E.Camera.move(k,{x:h.renderPos.value.x-~~(k.size.x/2),y:h.renderPos.value.y-~~(k.size.y/2)},a,1500,F.outQuart)}E.Camera.update(k,a)},render(a){a.bkg(0,0,0);b.TileMap.draw(a,k,z);a.col=4294967295;b.Texture.draw(a,v.TextureStore.test,0,0);b.Texture.draw(a,v.TextureStore.test2,48,0);b.Texture.draw(a,v.TextureStore.test3,80,0);b.Texture.draw(a,v.TextureStore.test2,
48,64,{x:2,y:1.5});b.Texture.draw(a,b.SpriteStore.dude01.currentFrame.texture,40-k.position.x,72-k.position.y);b.Texture.draw(a,b.SpriteStore.dude02.currentFrame.texture,h.renderPos.value.x-k.position.x,h.renderPos.value.y-k.position.y);b.Texture.draw(a,b.SpriteStore.dude01.currentFrame.texture,272-k.position.x,72-k.position.y);a.col=4294936712;b.NinePatch.draw(a,b.NinePatchStore.dialog,0,18,40,4);a.col=4294967295;b.Text.draw(a,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu condimentum purus, eu pharetra arcu. Mauris imperdiet consectetur odio sed volutpat.",
6,150,b.Text.Alignment.LEFT,308)}}})(M||(M={}));
(function(a){var e=E.Core,c=E.Graphics,d=E.Assets;let f=[{name:"dude01",animations:{DEFAULT:[{texture:"guy_stand",duration:0}],walk:[{texture:"guy_01",duration:250},{texture:"guy_02",duration:250}]}},{name:"dude02",animations:{DEFAULT:[{texture:"guy_stand",duration:0}],walk:[{texture:"guy_stand",duration:250},{texture:"guy_01",duration:250},{texture:"guy_stand",duration:250},{texture:"guy_02",duration:250}]}}];a.setup=function(){e.addScene(M.MainMenu);e.addScene(M.Main);for(let a of f)c.Sprite.CreateAndStore(a);
E.Tile.CreateAndStore("north_wall",d.TextureStore.brick,4281545642,!0);E.Tile.CreateAndStore("wall",d.TextureStore.brick,4278321666,!0);E.Tile.CreateAndStore("floor",d.TextureStore.brick,4279176975,!1);c.SpriteStore.dude01.play("walk",!0);c.SpriteStore.dude02.play("walk",!0);c.NinePatchStore.dialog={tl:d.TextureStore.dialog_tl,tc:d.TextureStore.dialog_t,tr:d.TextureStore.dialog_tr,ml:d.TextureStore.dialog_ml,mc:d.TextureStore.dialog_m,mr:d.TextureStore.dialog_mr,bl:d.TextureStore.dialog_bl,bc:d.TextureStore.dialog_b,
br:d.TextureStore.dialog_br};e.pushScene("MainMenu")}})(N||(N={}));
(function(a){var e=E.Core,c=E.Input,d=E.Assets;let f={alpha:{loc:"res/alpha.png",sWidth:5,sHeight:5,textures:["abcdefghijklmnopqrstuvwxyz".split(""),"1234567890.!?#()-^+\x3d/\\:,'\"".split("")]},tiles:{loc:"res/test.png",sWidth:8,sHeight:8,textures:[["brick","guy_stand","guy_01","guy_02"],["dialog_tl","dialog_t","dialog_tr","blank03"],["dialog_ml","dialog_m","dialog_mr","blank04"],["dialog_bl","dialog_b","dialog_br","blank05"]]},irreg:{loc:"res/irreg.png",textures:[{name:"test",x:0,y:0,width:32,height:32},
{name:"test2",x:16,y:32,width:16,height:32},{name:"test3",x:32,y:0,width:64,height:64}]}};a.onload=function(){function g(){var a=e._gl.canvas,c=0|Math.min(window.innerWidth/a.width,window.innerHeight/a.height);c=0>=c?1:c;a=[a.width*c,a.height*c];a=[(window.innerWidth-a[0])/2,(window.innerHeight-a[1])/2];c="translate("+~~a[0]+"px, "+~~a[1]+"px) scale("+~~c+")";a=document.getElementById("stage");a.style.transform=c;a.style.webkitTransform=c}e.init(document.getElementById("canvas"));c.Controls.UP=[38,
87];c.Controls.DOWN=[40,83];c.Controls.LEFT=[37,65];c.Controls.RIGHT=[39,68];c.Controls.ACTION=[13,32];d.load(f,()=>{window.onresize=g;g();e.start();a.setup()})}})(N||(N={}));window.onload=N.onload;
})()