(function(){
'use strict';var l,u;function z(a){return{x:a.x,y:a.y}}function A(a,c){return{x:a.x*c,y:a.y*c}}function C(a,c){return{x:~~(a.x/c),y:~~(a.y/c)}}function D(a,c){return Math.floor(Math.random()*(c-a+1))+a}function F(a,c,f,e){return((((0|255&e)<<8>>>0|255&f)<<8>>>0|255&c)<<8>>>0|255&a)>>>0}
!function(a){a.StateMachine=class{constructor(){this._stateDictionary={};this._stateStack=[]}reset(){this._stateDictionary={};this._stateStack.length=0}register(a){this._stateDictionary[a.name]=a}get current(){return this._stateStack[this._stateStack.length-1]}push(a,...f){this.current&&this.current.transitionOut&&this.current.transitionOut();(a=this._stateDictionary[a])&&a.transitionIn&&a.transitionIn(...f);this._stateStack.push(a)}pop(...a){if(this.current&&this.current.transitionOut&&this.current.transitionOut(),
2>this._stateStack.length)return null;var c=this._stateStack[this._stateStack.length-2];return c&&c.transitionIn&&c.transitionIn(...a),this._stateStack.pop()}}}(I||(I={}));(function(a){a.add=function(a,f){return{x:a.x+f.x,y:a.y+f.y}};a.sub=function(a,f){return{x:a.x-f.x,y:a.y-f.y}}})(l||(l={}));(function(a){a.get=function(a,f,e){return(a&e)>>f};a.clear=function(a,f){return a&~f};a.set=function(a,f,e,b){return a&~b|f<<e}})(u||(u={}));
const J={linear:function(a){return a},inQuad:function(a){return a*a},outQuad:function(a){return a*(2-a)},inOutQuad:function(a){return.5>a?2*a*a:(4-2*a)*a-1},inCubic:function(a){return a*a*a},outCubic:function(a){return--a*a*a+1},inOutCubic:function(a){return.5>a?4*a*a*a:(a-1)*(2*a-2)*(2*a-2)+1},inQuart:function(a){return a*a*a*a},outQuart:function(a){return 1- --a*a*a*a},inOutQuart:function(a){return.5>a?8*a*a*a*a:1-8*--a*a*a*a},inQuint:function(a){return a*a*a*a*a},outQuint:function(a){return 1+
--a*a*a*a*a},inOutQuint:function(a){return.5>a?16*a*a*a*a*a:1+16*--a*a*a*a*a}};function*L(a,c,f){let e;for(e=yield 0;e-a<c;)e=yield f((e-a)/c);if(e-a>=c)return 1}var I,O,R,S,T,V;
!function(a){!function(a){function c(b,a,d){d=b.createShader(d);return b.shaderSource(d,a),b.compileShader(d),d}function e(b,a,d){var g=b.createProgram();a=c(b,a,35633);d=c(b,d,35632);return b.attachShader(g,a),b.attachShader(g,d),b.linkProgram(g),g}function b(b,a,d,g){var e=b.createBuffer();return b.bindBuffer(a,e),b.bufferData(a,d,g),e}a.CompileShader=c;a.CreateShaderProgram=e;a.CreateBuffer=b;a.CreateTexture=function(b,a){var d=b.createTexture();return b.bindTexture(3553,d),b.texParameteri(3553,
10242,33071),b.texParameteri(3553,10243,33071),b.texParameteri(3553,10240,9728),b.texParameteri(3553,10241,9728),b.texImage2D(3553,0,6408,6408,5121,a),b.bindTexture(3553,null),d};a.Renderer=function(a){var h,d=a.getContext("webgl"),g=a.width,k=a.height,c=e(d,"precision lowp float;                  \n                    \n                    // IN Vertex Position and\n                    // IN Texture Coordinates\n                    attribute vec2 a, b;\n                    \n                    // IN Vertex Color\n                    attribute vec4 c;\n\n                    // IN Light Value\n                    attribute vec3 _l;\n                    \n                    // OUT Texture Coordinates\n                    varying vec2 d;\n                    \n                    // OUT Vertex Color\n                    varying vec4 e;\n                    \n                    // OUT Light Value\n                    varying vec3 l;\n                    \n                    // CONST View Matrix\n                    uniform mat4 m;\n                    uniform vec2 r;\n                    \n                    void main(){\n                        gl_Position\x3dm*vec4(a,1.0,1.0);\n                        d\x3db;\n                        e\x3dc;\n                        l\x3d_l;\n                    }",
"precision lowp float;\n                        // OUT Texture Coordinates\n                        varying vec2 d;\n                        \n                        // OUT Vertex Color\n                        varying vec4 e;\n                        \n                        // OUT Light Strength\n                        varying vec3 l;\n                        \n                        // CONST Single Sampler2D\n                        uniform sampler2D f;\n\n                        void main(){\n                            gl_FragColor\x3dtexture2D(f,d)*e;\n                            gl_FragColor.rgb*\x3dl;\n                        }"),
f=d.bufferSubData.bind(d),P=d.drawElements.bind(d),G=d.bindTexture.bind(d),E=d.clear.bind(d),H=d.clearColor.bind(d),K=new ArrayBuffer(1398016),q=new Float32Array(K),M=new Uint32Array(K);var x=new Uint16Array(131064);var v=b(d,34963,x.byteLength,35044);var B=b(d,34962,K.byteLength,35048);var y=0,n=new Float32Array([1,0,0,1,0,0]),w=new Float32Array(100),t=0,W=Math.cos,X=Math.sin,Q=null;d.blendFunc(770,771);d.enable(3042);d.useProgram(c);d.bindBuffer(34963,v);for(h=v=0;65532>v;v+=6,h+=4)x[v+0]=h,x[v+
1]=h+1,x[v+2]=h+2,x[v+3]=h+0,x[v+4]=h+3,x[v+5]=h+1;f(34963,0,x);d.bindBuffer(34962,B);x=d.getAttribLocation(c,"a");B=d.getAttribLocation(c,"b");v=d.getAttribLocation(c,"c");h=d.getAttribLocation(c,"_l");d.enableVertexAttribArray(x);d.vertexAttribPointer(x,2,5126,!1,32,0);d.enableVertexAttribArray(B);d.vertexAttribPointer(B,2,5126,!1,32,8);d.enableVertexAttribArray(v);d.vertexAttribPointer(v,4,5121,!0,32,16);d.uniformMatrix4fv(d.getUniformLocation(c,"m"),!1,new Float32Array([2/g,0,0,0,0,-2/k,0,0,0,
0,1,1,-1,1,0,0]));d.enableVertexAttribArray(h);d.vertexAttribPointer(h,3,5126,!1,32,20);d.activeTexture(33984);let U={gl:d,canvas:a,col:4294967295,bkg:function(b,d,a){H(b,d,a,1)},cls:function(){E(16384)},trans:function(b,d){n[4]=n[0]*b+n[2]*d+n[4];n[5]=n[1]*b+n[3]*d+n[5]},scale:function(b,d){n[0]*=b;n[1]*=b;n[2]*=d;n[3]*=d},rot:function(b){var d=n[0],a=n[1],e=n[2],g=n[3],h=X(b);b=W(b);n[0]=d*b+e*h;n[1]=a*b+g*h;n[2]=d*-h+e*b;n[3]=a*-h+g*b},push:function(){w[t+0]=n[0];w[t+1]=n[1];w[t+2]=n[2];w[t+3]=
n[3];w[t+4]=n[4];w[t+5]=n[5];t+=6},pop:function(){t-=6;n[0]=w[t+0];n[1]=w[t+1];n[2]=w[t+2];n[3]=w[t+3];n[4]=w[t+4];n[5]=w[t+5]},img:function(b,d,a,e,g,h,k,c,r,m={x:1,y:1,z:1}){var p=d+e,E=a+g;g=a+g;e=d+e;var H=n[0],t=n[1],v=n[2],w=n[3],x=n[4],B=n[5],N=U.col;(b!=Q||10922<=y+1)&&(f(34962,0,K),P(4,6*y,5123,0),y=0,Q!=b&&G(3553,Q=b));b=32*y;q[b++]=d*H+a*v+x;q[b++]=d*t+a*w+B;q[b++]=h;q[b++]=k;M[b++]=N;q[b++]=m.x;q[b++]=m.y;q[b++]=m.z;q[b++]=p*H+E*v+x;q[b++]=p*t+E*w+B;q[b++]=c;q[b++]=r;M[b++]=N;q[b++]=m.x;
q[b++]=m.y;q[b++]=m.z;q[b++]=d*H+g*v+x;q[b++]=d*t+g*w+B;q[b++]=h;q[b++]=r;M[b++]=N;q[b++]=m.x;q[b++]=m.y;q[b++]=m.z;q[b++]=e*H+a*v+x;q[b++]=e*t+a*w+B;q[b++]=c;q[b++]=k;M[b++]=N;q[b++]=m.x;q[b++]=m.y;q[b++]=m.z;10922<=++y&&(f(34962,0,K),P(4,6*y,5123,0),y=0)},flush:function(){0!=y&&(f(34962,0,q.subarray(0,32*y)),P(4,6*y,5123,0),y=0)}};return U}}(a.GL||(a.GL={}))}(I||(I={}));
(function(a){!function(c){c.TextureAtlasStore={};c.TextureStore={};c.load=function(f,e){let b=0,k=()=>{0>=--b&&e()};for(let d in f){let e=new Image;var h=f[d];e.onload="sWidth"in h&&"sHeight"in h?function(b,d,e){let g=f[b];return()=>{let h=a.GL.CreateTexture(a.Core._gl.gl,d,d.width,d.height),k=g.textures;c.TextureAtlasStore[b]=h;for(let b=0;b<k.length;b++)for(let a=0;a<k[b].length;a++)c.TextureStore[k[b][a]]={atlas:h,w:g.sWidth,h:g.sHeight,u0:a*g.sWidth/d.width,v0:b*g.sHeight/d.height,u1:(a*g.sWidth+
g.sWidth)/d.width,v1:(b*g.sHeight+g.sHeight)/d.height};e()}}(d,e,k):function(b,d,e){let g=f[b];return()=>{let h=a.GL.CreateTexture(a.Core._gl.gl,d,d.width,d.height),k=g.textures;c.TextureAtlasStore[b]=h;for(let b of k)c.TextureStore[b.name]={atlas:h,w:b.width,h:b.height,u0:b.x/d.width,v0:b.y/d.height,u1:(b.x+b.width)/d.width,v1:(b.y+b.height)/d.height};e()}}(d,e,k);b++;e.src=f[d].loc}}}(a.Assets||(a.Assets={}))})(I||(I={}));
(function(a){!function(c){function f(b,a,e,d){let g=[];var h=Math.abs(e-b),k=Math.abs(d-a),c=b,f=a,G=1+h+k;b=b<e?1:-1;a=a<d?1:-1;d=h-k;h*=2;for(k*=2;0<G;)g.push({x:c,y:f}),0<d?(c+=b,d-=k):(f+=a,d+=h),--G;return g}function e(b,a,e){let d=[],g=0,h=~~(1-e);for(;g<=e;)d.push({x:e+b,y:g+a}),d.push({x:g+b,y:e+a}),d.push({x:-e+b,y:g+a}),d.push({x:-g+b,y:e+a}),d.push({x:-e+b,y:-g+a}),d.push({x:-g+b,y:-e+a}),d.push({x:e+b,y:-g+a}),d.push({x:g+b,y:-e+a}),g+=1,h+=0>=h?2*g+1:2*(g- --e)+1;return d}c.calculateLight=
function(b,k){b.a=[];let h=e(b.position.x,b.position.y,b.radius);for(let d in h){let e=f(b.position.x,b.position.y,h[d].x,h[d].y),c=b.intensity/e.length,m=0;for(let d in e){if(0>e[d].x||e[d].x>=k.mapSize.x||0>e[d].y||e[d].y>=k.mapSize.y)break;let g=e[d].y*k.mapSize.x+e[d].x,h=c*(e.length-parseInt(d)),f=a.TileMap.getTile(k,{x:e[d].x,y:e[d].y});if(f.hasCollision&&0<m)break;if(g in b.a&&!(b.a[g]>h)||(b.a[g]=1<h?1:h),f.hasCollision)break;if(f.hasCollision&&1<m)break;if(f.hasCollision&&m++,!f)break}}};
c.calculateLightMap=function(b){let a=[];for(let e in b)for(let d in b[e].a)(!a[d]||a[d]>b[e].a[d])&&(a[d]=b[e].a[d]);return a};c.pointsOnLine=f;c.pointsOnCircle=e}(a.Lighting||(a.Lighting={}))})(I||(I={}));
(function(a){!function(a){!function(a){a.Position=class{constructor(b,a,e=!0){this.name=b;this.value=a;this.active=e}};a.Tag=class{constructor(b){this.value=this.name=b}};a.Flag=class{constructor(b,a){this.name=b;this.value=a}};a.Number=class{constructor(b,a){this.name=b;this.value=a}};a.Object=class{constructor(b,a){this.name=b;this.value=a}};a.coalesceValue=function(b,a){return null!=b?b.value:a}}(a.Component||(a.Component={}));class c{constructor(a){this._components={};this.id=c.__id++;this._manager=
a||null}SetManager(a){null!=this._manager&&this.DetachManager();this._manager=a;for(let b in this._components)this.registerComponentWithManager(this._components[b])}DetachManager(){for(let a in this._manager.collections){let b=this._manager.collections[a].indexOf(this);-1!==b&&this._manager.collections[a].splice(b,1)}this._manager=null}registerComponentWithManager(a){null==this._manager.collections[a.name]&&(this._manager.collections[a.name]=[]);this._manager.collections[a.name].push(this);this._manager.emit(this,
a.name,"added")}addComponent(a){return this._components[a.name]=a,null!=this._manager&&this.registerComponentWithManager(a),a}getComponent(a){return null==this._components[a]?null:this._components[a]}hasComponent(a){return null!=this._components[a]}}c.__id=1;a.Entity=c;a.Manager=class{constructor(){this.collections={};this._eventHandlers={};this.entities=[]}reset(){this.collections={};this._eventHandlers={};this.entities.length=0}addEntity(a){return null==a?a=new c(this):a.SetManager(this),this.entities[a.id]=
a,a}getAll(a){return this.collections[a]?this.collections[a]:[]}getFirst(a){return null==this.collections[a]?null:this.collections[a][0]}on(a,b,c){null==this._eventHandlers[a]&&(this._eventHandlers[a]={});null==this._eventHandlers[a][b]&&(this._eventHandlers[a][b]=[]);this._eventHandlers[a][b].push(c)}emit(a,b,c){this._eventHandlers[b]&&this._eventHandlers[b][c]&&this._eventHandlers[b][c].forEach((e)=>{e(a,this.collections[b],c)})}}}(a.ECS||(a.ECS={}))})(I||(I={}));
(function(a){a.TileStorage={};a.TileNames={};(function(c){let f;!function(a){a.draw=function(b,a,e,d,g){c.Texture.draw({renderer:b,texture:e,position:{x:d*e.w-a.position.x,y:g*e.h-a.position.y}})}}(f=c.Tile||(c.Tile={}));(function(e){e.draw=function(b,e,h){let d=C(e.position,h.tileSize),g=C(e.size,h.tileSize);for(let c=d.x;c<=d.x+g.x;c++)for(let k=d.y;k<=d.y+g.y;k++){let d=a.TileMap.getTile(h,{x:c,y:k});null!=d&&(b.col=d.colour,f.draw(b,e,d.texture,c,k))}}})(c.TileMap||(c.TileMap={}))})(a.Graphics||
(a.Graphics={}));(function(c){function f(){return e.next().value}let e=function*(){let b=0;for(;;)yield b++}();c.NextTileId=f;c.CreateAndStore=function(b,e,c,d){e={id:f(),texture:e,colour:c,hasCollision:d};return a.TileStorage[b]=e,a.TileNames[e.id]=b,e}})(a.Tile||(a.Tile={}));!function(c){let f=[];c.addTile=function(a,b,c){c=c.x+c.y*a.mapSize.x;void 0===a.tiles[c]&&(a.tiles[c]=0);a.tiles[c]|=b.hasCollision?1:0;a.tiles[c]|=b.id<<1};c.getTile=function(e,b){return b.x>=e.mapSize.x||b.y>=e.mapSize.y||
0>b.x||0>b.y?null:a.TileStorage[a.TileNames[(255&e.tiles[b.x+b.y*e.mapSize.x])>>1]]};c.getEntities=function(a,b){b=u.get(a.tiles[b.x+b.y*a.mapSize.x],8,268435200);a=[];for(b=f[b];b;)a.push(b.ecs),b=b.next;return a};c.mapEntity=function(a,b,c){let e=f[a.id]||{next:null,ecs:a,position:c,previous:null};if(null!=f[a.id]){var d=e.position.x+e.position.y*b.mapSize.x;u.get(b.tiles[d],8,268435200)==e.ecs.id&&(b.tiles[d]=u.clear(b.tiles[d],268435200),e.next&&(b.tiles[d]=u.set(b.tiles[d],e.next.ecs.id,8,268435200)));
e.next&&(e.next.previous=e.previous);e.previous&&(e.previous.next=e.next);e.next=e.previous=null}d=c.x+c.y*b.mapSize.x;var g=u.get(b.tiles[d],8,268435200);0!==g&&(b.tiles[d]=u.clear(b.tiles[d],268435200),g=f[g],e.next=g,g.previous=e);e.position=z(c);b.tiles[d]=u.set(b.tiles[d],a.id,8,268435200);f[a.id]=e}}(a.TileMap||(a.TileMap={}))})(I||(I={}));
(function(a){!function(a){function c(a,b){b=a.interpolator.next(b);let e=a.origin,c=a.target;a.position.x=e.x+Math.round((c.x-e.x)*b.value);a.position.y=e.y+Math.round((c.y-e.y)*b.value);1==b.done&&(a.moving=!1,a.position=z(a.target),a.origin=z(a.target),a.interpolator=null)}a.create=function(a,b){return{position:a,origin:a,target:a,size:b,moving:!1,interpolator:null}};a.update=function(a,b){a.moving&&c(a,b)};a.move=function(a,b,c,h=0,d=(a)=>a){a.target=z(b);a.origin=z(a.position);a.interpolator=
L(c,h,d);a.moving=!0};a.interpolate=c}(a.Camera||(a.Camera={}))})(I||(I={}));
(function(a){!function(c){let f,e;c.SpriteStore={};c.NinePatchStore={};(function(a){function b(a){return Object.assign({},a)}a.clone=b;a.cloneArray=function(a){let d=[];return a.forEach((a)=>{d.push(b(a))}),d}})(f||(f={}));class b{constructor(a){this.animations={};this.animationQueue=[];this.animations.DEFAULT=a;this.play("DEFAULT")}clone(){let a=new b(this.animations.DEFAULT.clone());for(let b in this.animations)a.addAnimation(b,this.animations[b].clone());return a}get currentAnimation(){return this.animationQueue[0]}get currentFrame(){return this.currentAnimation.currentFrame}addAnimation(a,
b){this.animations[a]=b}play(a,b=!1){this.animationQueue.length=0;a=this.animations[a].clone();return a.loop=b,this.animationQueue.push(a),this}then(a,b=!1){a=this.animations[a].clone();return a.loop=b,this.animationQueue.push(a),this}next(){this.animationQueue.shift();0===this.animationQueue.length&&this.stop()}stop(){this.animationQueue.length=0;this.animationQueue.push(this.animations.DEFAULT)}update(a,b){this.currentAnimation.done&&this.next();this.currentAnimation.update(b)}setColour(a){for(let b in this.animations)this.animations[b].setColour(a);
this.animationQueue.forEach((b)=>{b.setColour(a)})}setRotation(a){for(let b in this.animations)this.animations[b].setRotation(a);this.animationQueue.forEach((b)=>{b.setRotation(a)})}}c.Sprite=b;(function(b){class h{constructor(a){this._duration=-1;this.progress=0;this.done=this.loop=!1;this.frames=a}get currentFrame(){if(0===this.duration)return this.frames[0];{let a=0;for(let b in this.frames)if(a+=this.frames[b].duration,this.progress<=a)return this.frames[b];return this.frames[this.frames.length-
1]}}get duration(){if(-1===this._duration){this._duration=0;for(let a of this.frames)this._duration+=a.duration}return this._duration}clone(){return new h(f.cloneArray(this.frames))}update(a){if(this.done=!1,0===this.duration)return this.frames[0];this.progress+=a;this.progress>this.duration&&(this.loop?this.progress=0:(this.progress=0,this.done=!0))}setColour(a){this.frames.forEach((b)=>{b.colour=a})}setRotation(a){this.frames.forEach((b)=>{b.rotation=a})}}b.Animation=h;b.draw=function(a,b,c,f={x:0,
y:0}){a.col=b.currentFrame.colour;e.draw({renderer:a,texture:b.currentFrame.texture,position:l.sub(c,f),rotation:b.currentFrame.rotation})};b.CreateAndStore=function(d){let e=new b(new b.Animation([{texture:a.Assets.TextureStore[d.animations.DEFAULT[0].texture],colour:d.animations.DEFAULT[0].colour||4294967295,duration:d.animations.DEFAULT[0].duration}]));for(let c in d.animations){let g=d.animations[c],f=[];for(let b of g)f.push({texture:a.Assets.TextureStore[b.texture],colour:b.colour||4294967295,
duration:b.duration});e.addAnimation(c,new b.Animation(f))}return c.SpriteStore[d.name]=e,e}})(b=c.Sprite||(c.Sprite={}));(function(a){a.draw=function(a,b,c,f,k,p){k=c+k-1;let d=f+p-1;for(let g=c;g<=k;g++)for(let h=f;h<=d;h++)p=g===c?h===f?b.tl:h===d?b.bl:b.ml:g===k?h===f?b.tr:h===d?b.br:b.mr:h===f?b.tc:h===d?b.bc:b.mc,e.draw({renderer:a,texture:p,position:{x:g*p.w,y:h*p.h}})}})(c.NinePatch||(c.NinePatch={}));(function(a){a.draw=function(a){let b=a.texture,c=b.w,e=~~(c/2),f=b.h,h=~~(f/2),k=a.renderer,
G=a.light?a.light:{x:1,y:1,z:1},E=a.position;k.push();k.trans(E.x+e,E.y+h);a.scale&&k.scale(a.scale.x,a.scale.y);a.rotation&&k.rot(a.rotation);k.img(b.atlas,-e,-h,c,f,b.u0,b.v0,b.u1,b.v1,G);k.pop()}})(e=c.Texture||(c.Texture={}));(function(b){let c;!function(a){a[a.LEFT=0]="LEFT";a[a.CENTER=1]="CENTER";a[a.RIGHT=2]="RIGHT"}(c=b.Alignment||(b.Alignment={}));b.draw=function(b,e,f,h=c.LEFT,k=0){f=z(f);let d=e.split(" "),g=f.x,r=0,m=0==k?6*e.split("").length:k;e=0;h==c.CENTER?e=~~(-m/2):h===c.RIGHT&&
(e=~~-m);for(let c of d){0!=k&&r+6*c.length>k&&(f.y+=6,r=0);for(let d of c.split(""))h=d.toLowerCase(),h=a.Assets.TextureStore[h],f.x=g+r,b.push(),b.trans(f.x,f.y),b.img(h.atlas,e,0,h.w,h.h,h.u0,h.v0,h.u1,h.v1),b.pop(),r+=6;r+=6}}})(c.Text||(c.Text={}))}(a.Graphics||(a.Graphics={}))})(I||(I={}));
(function(a){!function(a){a.Manager=class{constructor(){this.subscribers={}}reset(){this.subscribers={}}};a.emit=function(a,c,b,...k){a.subscribers[c]&&a.subscribers[c][b]&&a.subscribers[c][b].forEach((a)=>{a(...k)})};a.on=function(a,c,b,k){null==a.subscribers[c]&&(a.subscribers[c]={});null==a.subscribers[c][b]&&(a.subscribers[c][b]=[]);a.subscribers[c][b].push(k)}}(a.Events||(a.Events={}))})(I||(I={}));
(function(a){var c=a.Graphics;a.Scene=class{constructor(f){this.ecsManager=new a.ECS.Manager;this.eventManager=new a.Events.Manager;this.subSceneManager=new a.StateMachine;this._storage={};this.transitionIn=f.transitionIn;this.transitionOut=()=>{this._storage={};this.ecsManager.reset();this.eventManager.reset();this.subSceneManager.reset();f.transitionOut()};this.update=f.update;this.render=(e,b,k)=>{let h=a.Camera.current;e.bkg(0,0,0);e.col=4294967295;this.ecsManager.getAll("renderable").forEach((a)=>
{if(a.hasComponent("tileMap"))a=a.getComponent("tileMap").value,c.TileMap.draw(e,h,a);else if(a.hasComponent("sprite")){var b=a.getComponent("sprite").value;a=a.getComponent("renderPos").value;c.Sprite.draw(e,b,a,h.position)}else a.hasComponent("text")?(b=a.getComponent("text").value,a=a.getComponent("renderPos").value,e.col=b.colour,c.Text.draw(e,b.text,a,b.textAlign,b.wrapWidth)):a.hasComponent("9patch")&&(b=a.getComponent("9patch").value,a=a.getComponent("tilePos").value,e.col=b.colour,c.NinePatch.draw(e,
c.NinePatchStore[b.name],a.x,a.y,b.tileSize.x,b.tileSize.y))});f.render(e,b,k);this.subSceneManager.current&&this.subSceneManager.current.render(e,b,k)};this.name=f.name}attach(a,c){return this._storage[a]=c,c}modify(a,c){return this._storage[a]=c,c}fetch(a){return this._storage[a]}}})(I||(I={}));
(function(a){!function(a){function c(a){d||(a=a.which,h[a]&&b[a]&&b[a].keyDown(),h[a]=!1,k[a]=!0)}function e(a){d||(a=a.which,b[a]&&b[a].keyUp(),k[a]=!1,h[a]=!0)}a.Controls={};let b=[],k=[],h=[],d=!1;for(let a=0;256>a;a++)h[a]=!0;window.onkeydown=c;window.onkeyup=e;a.keyDown=c;a.keyUp=e;a.disable=function(){d=!0;k.forEach((a,c,d)=>{a&&b[c]&&b[c].keyUp();d[c]=!1});h.forEach((a,b,c)=>{c[b]=!0})};a.enable=function(){d=!1};a.bindKey=function(a,c,d=()=>{}){b[a]={keyDown:c,keyUp:d}};a.unbindKey=function(a){delete b[a]};
a.unbindAll=function(){b.forEach((a,c)=>{73!==c&&delete b[c]})};a.bindControl=function(c,d,e=()=>{}){for(let f of a.Controls[c])b[f]={keyDown:d,keyUp:e}};a.unbindControl=function(c){for(let d of a.Controls[c])delete b[d]}}(a.Input||(a.Input={}))})(I||(I={}));
(function(a){!function(c){function f(e){if(g){let g=e-k;k=e;d||function(a,c){let d=b.current;d&&d.update(a,c)}(e,g);(function(e,f){let g=b.current;(c._gl.cls(),d)?(e=~~(c.WIDTH/2),f=~~(c.HEIGHT/2),c._gl.col=4294967295,a.Graphics.Text.draw(c._gl,"game paused",{x:e,y:f-8},a.Graphics.Text.Alignment.CENTER),a.Graphics.Text.draw(c._gl,"click here to resume",{x:e,y:f+8},a.Graphics.Text.Alignment.CENTER)):g&&g.render(c._gl,e,f);c._gl.flush()})(e,g);requestAnimationFrame(f)}}let e,b,k,h;c.WIDTH=0;c.HEIGHT=
0;c.addScene=function(a){b.register(a)};c.pushScene=function(a,...c){b.push(a,...c)};c.popScene=function(){b.pop()};let d=!1,g=!1;c.init=function(d){e=d;c._gl=a.GL.Renderer(e);a.Camera.current=a.Camera.create({x:0,y:0},{x:c.WIDTH,y:c.HEIGHT});b=new a.StateMachine;c.WIDTH=c._gl.canvas.width;c.HEIGHT=c._gl.canvas.height};c.start=function(){k=performance.now();c._gl.bkg(0,0,0);g=!0;h=requestAnimationFrame(f)};c.stop=function(){g=!1;cancelAnimationFrame(h)};c.pause=function(){d=!0;a.Input.disable()};
c.unpause=function(){d=!1;a.Input.enable()}}(a.Core||(a.Core={}))})(I||(I={}));(function(a){var c=null;a.setStorage=function(a){c=a};a.newGame=function(){V.gameState={version:"0.0.0",wallPoints:0,towerPoints:0,upgradePoint:0}};a.save=function(){c.setItem("save",JSON.stringify(V.gameState))};a.saveExists=function(){var a=c.getItem("save");return null!=a&&""!=a};a.load=function(){var a=c.getItem("save");V.gameState=JSON.parse(a)}})(O||(O={}));
(function(a){var c=I,f=c.Core,e=c.Input,b=c.Graphics,k=I.ECS.Component;a.TitleMenu=new c.Scene({name:"TitleMenu",transitionIn(){let a=this,c=0,g=[];g=O.saveExists()?["Continue","New Game","Settings"]:["New Game","Settings"];a.attach("menuOptions",g);let r=~~(f.HEIGHT/2),m=a.ecsManager;var p=m.addEntity();p.addComponent(new k.Position("tilePos",{x:0,y:0}));p.addComponent(new k.Object("9patch",{name:"dialog",colour:4294901760,tileSize:{x:32,y:18}}));p.addComponent(new k.Number("sort",0));p.addComponent(new k.Tag("renderable"));
p=m.addEntity();p.addComponent(new k.Position("renderPos",{x:16,y:16}));p.addComponent(new k.Object("text",{text:"Tower Defense",textAlign:b.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295}));p.addComponent(new k.Number("sort",10));p.addComponent(new k.Tag("renderable"));g.forEach((d,e)=>{let g=m.addEntity();g.addComponent(new k.Position("renderPos",{x:32,y:r+16*e}));let f=d;c===e&&(f=`(${f})`);let h=g.addComponent(new k.Object("text",{text:f,textAlign:b.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295}));
g.addComponent(new k.Number("sort",10));g.addComponent(new k.Tag("renderable"));I.Events.on(a.eventManager,"sel","change",(a)=>{h.value.text=e==a?`(${d})`:d})});e.bindControl("DOWN",()=>{(c+=1)>g.length-1&&(c=0);I.Events.emit(a.eventManager,"sel","change",c)});e.bindControl("UP",()=>{0>--c&&(c=g.length-1);I.Events.emit(a.eventManager,"sel","change",c)});e.bindControl("ACTION",()=>{switch(g[c]){case "Continue":O.load();f.pushScene("Game");break;case "New Game":O.newGame();f.pushScene("Game");break;
case "Settings":f.pushScene("SettingsMenu")}})},transitionOut(){e.unbindAll()},update(){},render(){}})})(T||(T={}));
(function(a){a.handlePlayerInput=function(a){let c=a.getComponent("tilePos"),b=a.getComponent("targetTile"),f=a.getComponent("moving"),h=a.getComponent("movingRight"),d=a.getComponent("movingLeft"),g=a.getComponent("movingUp");a=a.getComponent("movingDown");0==f.value&&(h.value&&b.value.x++,d.value&&b.value.x--,g.value&&b.value.y--,a.value&&b.value.y++,c.value.x==b.value.x&&c.value.y==b.value.y||(f.value=!0))};a.handleCollision=function(a,c){let b=a.getComponent("tilePos"),e=a.getComponent("targetTile"),
f=a.getComponent("moving"),d=a.getComponent("movingRight"),g=a.getComponent("movingLeft"),r=a.getComponent("movingUp");a=a.getComponent("movingDown");if(d.value||g.value){let a=I.TileMap.getTile(c,{x:e.value.x,y:b.value.y});a&&a.hasCollision&&(d.value=g.value=!1,e.value.x=b.value.x)}(r.value||a.value)&&(c=I.TileMap.getTile(c,{x:b.value.x,y:e.value.y}))&&c.hasCollision&&(r.value=a.value=!1,e.value.y=b.value.y);b.value.x===e.value.x&&b.value.y===e.value.y&&(f.value=!1)};let c={};a.moveEntity=function(a,
e,b){let f=a.getComponent("tilePos"),h=a.getComponent("targetTile"),d=a.getComponent("renderPos"),g=a.getComponent("moving");null==c[a.id]&&(c[a.id]={});null==c[a.id].moveFn&&(c[a.id].moveFn=L(b,160,J.linear));b=c[a.id].moveFn.next(b);let r=A(f.value,e.tileSize),m=A(h.value,e.tileSize);d.value.x=r.x+Math.round((m.x-r.x)*b.value);d.value.y=r.y+Math.round((m.y-r.y)*b.value);1==b.done&&(g.value=!1,f.value=z(h.value),d.value=A(f.value,e.tileSize),I.TileMap.mapEntity(a,e,f.value),delete c[a.id].moveFn)}})(R||
(R={}));
(function(a){!function(a){!function(a){var c=I.Input,b=I.ECS.Component,f=I.Graphics;a.Move=new I.Scene({name:"Move",transitionIn(a){let d=this;d.attach("parentScene",a);var e=a.ecsManager;let h=e.getFirst("player"),k=e.getFirst("levelMap").getComponent("tileMap").value;e=d.ecsManager.addEntity();e.addComponent(new b.Position("renderPos",{x:448,y:8}));e.addComponent(new b.Object("text",{text:"Move Mode",textAlign:f.Text.Alignment.CENTER,wrapWidth:0,colour:4294967295}));e.addComponent(new b.Number("sort",10));
e.addComponent(new b.Tag("renderable"));e=d.ecsManager.addEntity();e.addComponent(new b.Position("renderPos",{x:392,y:I.Core.HEIGHT-16}));e.addComponent(new b.Object("text",{text:"Space: Build",textAlign:f.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295}));e.addComponent(new b.Number("sort",10));e.addComponent(new b.Tag("renderable"));c.bindControl("RIGHT",()=>{h.getComponent("movingRight").value=!0},()=>{h.getComponent("movingRight").value=!1});c.bindControl("LEFT",()=>{h.getComponent("movingLeft").value=
!0},()=>{h.getComponent("movingLeft").value=!1});c.bindControl("DOWN",()=>{h.getComponent("movingDown").value=!0},()=>{h.getComponent("movingDown").value=!1});c.bindControl("UP",()=>{h.getComponent("movingUp").value=!0},()=>{h.getComponent("movingUp").value=!1});c.bindControl("ACTION",()=>{if(h.getComponent("movingUp").value=!1,h.getComponent("movingDown").value=!1,h.getComponent("movingLeft").value=!1,h.getComponent("movingRight").value=!1,h.getComponent("moving").value)window.setTimeout(()=>{let b=
h.getComponent("tilePos").value;0!==I.TileMap.getEntities(k,b).filter((a)=>a.hasComponent("blocking")).length||h.getComponent("moving").value||a.subSceneManager.push("Build",a)},160);else{let b=h.getComponent("tilePos").value;0===I.TileMap.getEntities(k,b).filter((a)=>a.hasComponent("blocking")).length&&a.subSceneManager.push("Build",a)}},()=>{});c.bindKey(73,()=>{},()=>{console.log(d.ecsManager)})},transitionOut(){c.unbindAll()},update(){},render(){}})}(a.SubScenes||(a.SubScenes={}))}(a.Game||(a.Game=
{}))})(T||(T={}));(function(a){var c=I.ECS,f=I.ECS.Component;a.Text=function(a,b,k=10){let e=new c.Entity;return e.addComponent(new f.Position("renderPos",a)),e.addComponent(new f.Object("text",b)),e.addComponent(new f.Number("sort",k)),e.addComponent(new f.Tag("renderable")),e}})(S||(S={}));
(function(a){!function(a){!function(a){var c=I.Input,b=I.ECS.Component,f=I.Graphics;a.Build=new I.Scene({name:"Build",transitionIn(a){let d=this;d.attach("parentScene",a);let e=d.ecsManager;var h=S.Text({x:448,y:8},{text:"Build Mode",textAlign:f.Text.Alignment.CENTER,wrapWidth:0,colour:4294967295});e.addEntity(h);h=S.Text({x:392,y:I.Core.HEIGHT-16},{text:"Esc: Back",textAlign:f.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295});e.addEntity(h);h=S.Text({x:392,y:I.Core.HEIGHT-24},{text:"Space: Confirm",
textAlign:f.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295});e.addEntity(h);let k=["Build Wall","Build Tower","Close"],p=0;k.forEach((a,c)=>{let h=e.addEntity();h.addComponent(new b.Position("renderPos",{x:448,y:32+16*c}));let g=a;p===c&&(g=`(${g})`);let k=h.addComponent(new b.Object("text",{text:g,textAlign:f.Text.Alignment.CENTER,wrapWidth:0,colour:4294967295}));h.addComponent(new b.Number("sort",10));h.addComponent(new b.Tag("renderable"));I.Events.on(d.eventManager,"sel","change",(b)=>{k.value.text=
c==b?`(${a})`:a})});c.bindControl("DOWN",()=>{(p+=1)>k.length-1&&(p=0);I.Events.emit(d.eventManager,"sel","change",p)});c.bindControl("UP",()=>{0>--p&&(p=k.length-1);I.Events.emit(d.eventManager,"sel","change",p)});c.bindControl("ACTION",()=>{switch(k[p]){case "Close":a.subSceneManager.pop(a)}},()=>{});c.bindControl("BACK",()=>{},()=>{a.subSceneManager.pop(a)})},transitionOut(){c.unbindAll()},update(){},render(){}})}(a.SubScenes||(a.SubScenes={}))}(a.Game||(a.Game={}))})(T||(T={}));
(function(a){!function(a){!function(a){a.Defend=new I.Scene({name:"Defend",transitionIn(a){this.attach("parentScene",a)},transitionOut(){},update(){},render(){}})}(a.SubScenes||(a.SubScenes={}))}(a.Game||(a.Game={}))})(T||(T={}));
(function(a){!function(a){var c=I,e=c.ECS,b=e.Component,k=c.Graphics;a.scene=new c.Scene({name:"Game",transitionIn(){let h=this.ecsManager;h.on("renderable","added",(a,b)=>{b.sort((a,b)=>e.Component.coalesceValue(a.getComponent("sort"),0)-e.Component.coalesceValue(b.getComponent("sort"),0))});let d={mapSize:{x:24,y:24},tileSize:16,tiles:[]};this.attach("cameraGap",7*d.tileSize);I.Camera.current=I.Camera.create({x:0,y:0},{x:24*d.tileSize,y:18*d.tileSize});(function(a){for(let b=0;b<a.mapSize.x;b++)for(let c=
0;c<a.mapSize.y;c++)b===a.mapSize.x-1||0===b||c===a.mapSize.y-1?I.TileMap.addTile(a,I.TileStorage.wall,{x:b,y:c}):0===c?I.TileMap.addTile(a,I.TileStorage.north_wall,{x:b,y:c}):I.TileMap.addTile(a,I.TileStorage.floor,{x:b,y:c})})(d);var g=h.addEntity();g.addComponent(new b.Tag("levelMap"));g.addComponent(new b.Object("tileMap",d));g.addComponent(new b.Number("sort",1));g.addComponent(new b.Tag("renderable"));g=h.addEntity();g.addComponent(new b.Position("tilePos",{x:24,y:0}));g.addComponent(new b.Object("9patch",
{name:"dialog",colour:4294936712,tileSize:{x:8,y:18}}));g.addComponent(new b.Number("sort",9));g.addComponent(new b.Tag("renderable"));g=h.addEntity();g.addComponent(new b.Tag("player"));var f=g.addComponent(new b.Position("tilePos",{x:1,y:1}));g.addComponent(new b.Position("renderPos",A(f.value,d.tileSize)));g.addComponent(new b.Position("targetTile",z(f.value)));g.addComponent(new b.Flag("moving",!1));g.addComponent(new b.Flag("movingLeft",!1));g.addComponent(new b.Flag("movingRight",!1));g.addComponent(new b.Flag("movingUp",
!1));g.addComponent(new b.Flag("movingDown",!1));var m=k.SpriteStore.cursor.clone();m.play("blink",!0);m.setColour(4278255360);g.addComponent(new b.Object("sprite",m));g.addComponent(new b.Number("sort",2));g.addComponent(new b.Tag("renderable"));c.TileMap.mapEntity(g,d,f.value);g=h.addEntity();g.addComponent(new b.Tag("blocking"));f=g.addComponent(new b.Position("tilePos",{x:1,y:1}));g.addComponent(new b.Position("renderPos",A(f.value,d.tileSize)));g.addComponent(new b.Position("targetTile",z(f.value)));
m=k.SpriteStore.spawner.clone();m.setColour(4278190335);g.addComponent(new b.Object("sprite",m));g.addComponent(new b.Number("sort",2));g.addComponent(new b.Tag("renderable"));c.TileMap.mapEntity(g,d,f.value);for(g=0;10>g;g++){f=h.addEntity();m=f.addComponent(new b.Position("tilePos",{x:-2,y:g+1}));f.addComponent(new b.Position("renderPos",A(m.value,d.tileSize)));{m=k.SpriteStore.cursor.clone();let a=F(D(50,255),D(50,255),D(50,255),D(175,255));0==g%2?m.play("blink",!0):m.play("quick-blink",!0);m.setColour(a);
f.addComponent(new b.Object("sprite",m))}f.addComponent(new b.Number("sort",3));f.addComponent(new b.Tag("renderable"))}for(g=0;10>g;g++)f=h.addEntity(),m=f.addComponent(new b.Position("tilePos",{x:1,y:g+2})),f.addComponent(new b.Position("renderPos",A(m.value,d.tileSize))),m=k.SpriteStore.arrow.clone(),m.setRotation(Math.PI),m.play("blink",!0),f.addComponent(new b.Object("sprite",m)),f.addComponent(new b.Number("sort",4)),f.addComponent(new b.Tag("renderable"));for(g=0;10>g;g++)f=h.addEntity(),m=
f.addComponent(new b.Position("tilePos",{x:g+2,y:g+2})),f.addComponent(new b.Position("renderPos",A(m.value,d.tileSize))),m=k.SpriteStore.arrow_diag.clone(),m.setRotation(Math.PI),m.play("blink",!0),f.addComponent(new b.Object("sprite",m)),f.addComponent(new b.Number("sort",4)),f.addComponent(new b.Tag("renderable"));this.subSceneManager.register(a.SubScenes.Move);this.subSceneManager.register(a.SubScenes.Build);this.subSceneManager.register(a.SubScenes.Defend);this.subSceneManager.push("Move",this)},
transitionOut(){},update(a,b){var c=this.ecsManager,d=c.getFirst("player"),e=c.getFirst("levelMap").getComponent("tileMap").value;let f=I.Camera.current,h=this.fetch("cameraGap");R.handlePlayerInput(d);c.getAll("sprite").forEach((c)=>{c.getComponent("sprite").value.update(a,b)});c=d.getComponent("moving");(c.value&&(R.handleCollision(d,e),c.value&&R.moveEntity(d,e,a)),f.moving)||(d=d.getComponent("renderPos").value,e=d.x-(f.position.x+~~(f.size.x/2)),c=d.y-(f.position.y+~~(f.size.y/2)),(e>=h||e<=
-h||c>=h||c<=-h)&&I.Camera.move(f,{x:d.x-~~(f.size.x/2),y:d.y-~~(f.size.y/2)},a,1200,J.outCubic));I.Camera.update(f,a)},render(){}})}(a.Game||(a.Game={}))})(T||(T={}));
(function(a){var c=I.Core,f=I.Input,e=I.Graphics,b=I.ECS.Component;a.SettingsMenu=new I.Scene({name:"SettingsMenu",transitionIn(){let a=this,h=0,d=["Back"],g=~~(c.HEIGHT/2),r=~~(c.WIDTH/2),m=a.ecsManager;var p=m.addEntity();p.addComponent(new b.Position("tilePos",{x:0,y:0}));p.addComponent(new b.Object("9patch",{name:"dialog",colour:4294901760,tileSize:{x:32,y:18}}));p.addComponent(new b.Number("sort",0));p.addComponent(new b.Tag("renderable"));p=m.addEntity();p.addComponent(new b.Position("renderPos",
{x:r,y:16}));p.addComponent(new b.Object("text",{text:"Settings",textAlign:e.Text.Alignment.CENTER,wrapWidth:0,colour:4294967295}));p.addComponent(new b.Number("sort",10));p.addComponent(new b.Tag("renderable"));d.forEach((c,d)=>{let f=m.addEntity();f.addComponent(new b.Position("renderPos",{x:r,y:g+16*d}));let k=c;h===d&&(k=`(${k})`);let p=f.addComponent(new b.Object("text",{text:k,textAlign:e.Text.Alignment.CENTER,wrapWidth:0,colour:4294967295}));f.addComponent(new b.Number("sort",10));f.addComponent(new b.Tag("renderable"));
I.Events.on(a.eventManager,"sel","change",(a)=>{p.value.text=d==a?`(${c})`:c})});f.bindControl("DOWN",()=>{(h+=1)>d.length-1&&(h=0);I.Events.emit(a.eventManager,"sel","change",h)});f.bindControl("UP",()=>{0>--h&&(h=d.length-1);I.Events.emit(a.eventManager,"sel","change",h)});f.bindControl("ACTION",()=>{switch(d[h]){case "Back":c.popScene()}})},transitionOut(){f.unbindAll()},update(){},render(){}})})(T||(T={}));
(function(a){var c=I,f=c.Core,e=c.Input,b=c.Graphics;a.PostGame=new c.Scene({name:"PostGame",transitionIn(){e.bindControl("ACTION",()=>{f.popScene();f.popScene()})},transitionOut(){e.unbindControl("ACTION")},update(){},render(a){a.col=4292682274;b.NinePatch.draw(a,b.NinePatchStore.dialog,0,0,32,18);a.col=4294967295;b.Text.draw(a,"Winner is you.",{x:~~(f.WIDTH/2),y:~~(f.HEIGHT/2)},b.Text.Alignment.CENTER)}})})(T||(T={}));
(function(a){var c=I.Core,f=I.Graphics,e=I.Assets;let b=[{name:"cursor",animations:{DEFAULT:[{texture:"cursor",duration:0}],blink:[{texture:"cursor_light",duration:250},{texture:"cursor",duration:250},{texture:"cursor_dark",duration:250},{texture:"cursor",duration:250}],"quick-blink":[{texture:"cursor_light",duration:150},{texture:"cursor",duration:150},{texture:"cursor_dark",duration:150},{texture:"cursor",duration:150}]}},{name:"spawner",animations:{DEFAULT:[{texture:"spawner",duration:0}]}},{name:"arrow",
animations:{DEFAULT:[{texture:"arrow_cart",duration:0}],blink:[{texture:"arrow_cart",colour:3710001919,duration:350},{texture:"arrow_cart",colour:2569151231,duration:350},{texture:"arrow_cart",colour:1428300543,duration:350},{texture:"arrow_cart",colour:2569151231,duration:350}]}},{name:"arrow_diag",animations:{DEFAULT:[{texture:"arrow_diag",duration:0}],blink:[{texture:"arrow_diag",colour:2283938559,duration:350},{texture:"arrow_diag",colour:1713513215,duration:350},{texture:"arrow_diag",colour:1143087871,
duration:350},{texture:"arrow_diag",colour:1713513215,duration:350}]}}];a.gameState=null;a.setup=function(){c.addScene(T.TitleMenu);c.addScene(T.SettingsMenu);c.addScene(T.Game.scene);c.addScene(T.PostGame);for(let a of b)f.Sprite.CreateAndStore(a);I.Tile.CreateAndStore("north_wall",e.TextureStore.brick,4281150765,!0);I.Tile.CreateAndStore("wall",e.TextureStore.brick,4281150765,!0);I.Tile.CreateAndStore("floor",e.TextureStore.brick,4278519045,!1);f.NinePatchStore.dialog={tl:e.TextureStore.dialog_tl,
tc:e.TextureStore.dialog_t,tr:e.TextureStore.dialog_tr,ml:e.TextureStore.dialog_ml,mc:e.TextureStore.dialog_m,mr:e.TextureStore.dialog_mr,bl:e.TextureStore.dialog_bl,bc:e.TextureStore.dialog_b,br:e.TextureStore.dialog_br};c.pushScene("TitleMenu")}})(V||(V={}));
(function(a){var c=I.Core,f=I.Input,e=I.Assets;let b={alpha:{loc:"res/alpha.png",sWidth:5,sHeight:5,textures:["abcdefghijklmnopqrstuvwxyz".split(""),"1234567890.!?#()-^+\x3d/\\:,'\"".split("")]},tiles:{loc:"res/test.png",sWidth:16,sHeight:16,textures:[["brick","cursor","cursor_dark","cursor_light"],["dialog_tl","dialog_t","dialog_tr","arrow_cart"],["dialog_ml","dialog_m","dialog_mr","arrow_diag"],["dialog_bl","dialog_b","dialog_br","spawner"]]},irreg:{loc:"res/irreg.png",textures:[{name:"test",x:0,
y:0,width:32,height:32}]}};a.onload=function(){function k(){var a=c._gl.canvas,b=0|Math.min(window.innerWidth/a.width,window.innerHeight/a.height);b=0>=b?1:b;a=[a.width*b,a.height*b];a=[(window.innerWidth-a[0])/2,(window.innerHeight-a[1])/2];b="translate("+~~a[0]+"px, "+~~a[1]+"px) scale("+~~b+")";a=document.getElementById("stage");a.style.transform=b;a.style.webkitTransform=b}c.init(document.getElementById("canvas"));O.setStorage(window.localStorage);f.Controls.UP=[38,87];f.Controls.DOWN=[40,83];
f.Controls.LEFT=[37,65];f.Controls.RIGHT=[39,68];f.Controls.ACTION=[13,32];f.Controls.BACK=[27];e.load(b,()=>{window.onresize=k;k();window.onblur=()=>{c.pause()};window.onfocus=()=>{c.unpause()};c.start();a.setup()})}})(V||(V={}));window.onload=V.onload;
})()