(function(){
'use strict';var k;function u(a){return{x:a.x,y:a.y}}function z(a,c){return{x:a.x*c,y:a.y*c}}function B(a,c){return{x:~~(a.x/c),y:~~(a.y/c)}}function C(a,c){return Math.floor(Math.random()*(c-a+1))+a}function E(a,c,f,e){return((((0|255&e)<<8>>>0|255&f)<<8>>>0|255&c)<<8>>>0|255&a)>>>0}
!function(a){a.StateMachine=class{constructor(){this._stateDictionary={};this._stateStack=[]}reset(){this._stateDictionary={};this._stateStack.length=0}register(a){this._stateDictionary[a.name]=a}get current(){return this._stateStack[this._stateStack.length-1]}push(a,...f){this.current&&this.current.transitionOut&&this.current.transitionOut();(a=this._stateDictionary[a])&&a.transitionIn&&a.transitionIn(...f);this._stateStack.push(a)}pop(...a){if(this.current&&this.current.transitionOut&&this.current.transitionOut(),
2>this._stateStack.length)return null;var c=this._stateStack[this._stateStack.length-2];return c&&c.transitionIn&&c.transitionIn(...a),this._stateStack.pop()}}}(H||(H={}));(function(a){a.add=function(a,f){return{x:a.x+f.x,y:a.y+f.y}};a.sub=function(a,f){return{x:a.x-f.x,y:a.y-f.y}}})(k||(k={}));
const J={linear:function(a){return a},inQuad:function(a){return a*a},outQuad:function(a){return a*(2-a)},inOutQuad:function(a){return.5>a?2*a*a:(4-2*a)*a-1},inCubic:function(a){return a*a*a},outCubic:function(a){return--a*a*a+1},inOutCubic:function(a){return.5>a?4*a*a*a:(a-1)*(2*a-2)*(2*a-2)+1},inQuart:function(a){return a*a*a*a},outQuart:function(a){return 1- --a*a*a*a},inOutQuart:function(a){return.5>a?8*a*a*a*a:1-8*--a*a*a*a},inQuint:function(a){return a*a*a*a*a},outQuint:function(a){return 1+
--a*a*a*a*a},inOutQuint:function(a){return.5>a?16*a*a*a*a*a:1+16*--a*a*a*a*a}};function*M(a,c,f){let e;for(e=yield 0;e-a<c;)e=yield f((e-a)/c);if(e-a>=c)return 1}var H,P,Q,R,T;
!function(a){!function(a){function c(b,a,d){d=b.createShader(d);return b.shaderSource(d,a),b.compileShader(d),d}function e(b,a,d){var g=b.createProgram();a=c(b,a,35633);d=c(b,d,35632);return b.attachShader(g,a),b.attachShader(g,d),b.linkProgram(g),g}function b(b,a,d,g){var e=b.createBuffer();return b.bindBuffer(a,e),b.bufferData(a,d,g),e}a.CompileShader=c;a.CreateShaderProgram=e;a.CreateBuffer=b;a.CreateTexture=function(b,a){var d=b.createTexture();return b.bindTexture(3553,d),b.texParameteri(3553,
10242,33071),b.texParameteri(3553,10243,33071),b.texParameteri(3553,10240,9728),b.texParameteri(3553,10241,9728),b.texImage2D(3553,0,6408,6408,5121,a),b.bindTexture(3553,null),d};a.Renderer=function(a){var h,d=a.getContext("webgl"),g=a.width,c=a.height,f=e(d,"precision lowp float;                  \n                    \n                    // IN Vertex Position and\n                    // IN Texture Coordinates\n                    attribute vec2 a, b;\n                    \n                    // IN Vertex Color\n                    attribute vec4 c;\n\n                    // IN Light Value\n                    attribute vec3 _l;\n                    \n                    // OUT Texture Coordinates\n                    varying vec2 d;\n                    \n                    // OUT Vertex Color\n                    varying vec4 e;\n                    \n                    // OUT Light Value\n                    varying vec3 l;\n                    \n                    // CONST View Matrix\n                    uniform mat4 m;\n                    uniform vec2 r;\n                    \n                    void main(){\n                        gl_Position\x3dm*vec4(a,1.0,1.0);\n                        d\x3db;\n                        e\x3dc;\n                        l\x3d_l;\n                    }",
"precision lowp float;\n                        // OUT Texture Coordinates\n                        varying vec2 d;\n                        \n                        // OUT Vertex Color\n                        varying vec4 e;\n                        \n                        // OUT Light Strength\n                        varying vec3 l;\n                        \n                        // CONST Single Sampler2D\n                        uniform sampler2D f;\n\n                        void main(){\n                            gl_FragColor\x3dtexture2D(f,d)*e;\n                            gl_FragColor.rgb*\x3dl;\n                        }"),
q=d.bufferSubData.bind(d),N=d.drawElements.bind(d),F=d.bindTexture.bind(d),D=d.clear.bind(d),G=d.clearColor.bind(d),I=new ArrayBuffer(1398016),r=new Float32Array(I),K=new Uint32Array(I);var x=new Uint16Array(131064);var v=b(d,34963,x.byteLength,35044);var A=b(d,34962,I.byteLength,35048);var y=0,p=new Float32Array([1,0,0,1,0,0]),w=new Float32Array(100),t=0,U=Math.cos,V=Math.sin,O=null;d.blendFunc(770,771);d.enable(3042);d.useProgram(f);d.bindBuffer(34963,v);for(h=v=0;65532>v;v+=6,h+=4)x[v+0]=h,x[v+
1]=h+1,x[v+2]=h+2,x[v+3]=h+0,x[v+4]=h+3,x[v+5]=h+1;q(34963,0,x);d.bindBuffer(34962,A);x=d.getAttribLocation(f,"a");A=d.getAttribLocation(f,"b");v=d.getAttribLocation(f,"c");h=d.getAttribLocation(f,"_l");d.enableVertexAttribArray(x);d.vertexAttribPointer(x,2,5126,!1,32,0);d.enableVertexAttribArray(A);d.vertexAttribPointer(A,2,5126,!1,32,8);d.enableVertexAttribArray(v);d.vertexAttribPointer(v,4,5121,!0,32,16);d.uniformMatrix4fv(d.getUniformLocation(f,"m"),!1,new Float32Array([2/g,0,0,0,0,-2/c,0,0,0,
0,1,1,-1,1,0,0]));d.enableVertexAttribArray(h);d.vertexAttribPointer(h,3,5126,!1,32,20);d.activeTexture(33984);let S={gl:d,canvas:a,col:4294967295,bkg:function(b,d,a){G(b,d,a,1)},cls:function(){D(16384)},trans:function(b,d){p[4]=p[0]*b+p[2]*d+p[4];p[5]=p[1]*b+p[3]*d+p[5]},scale:function(b,d){p[0]*=b;p[1]*=b;p[2]*=d;p[3]*=d},rot:function(b){var d=p[0],a=p[1],g=p[2],e=p[3],h=V(b);b=U(b);p[0]=d*b+g*h;p[1]=a*b+e*h;p[2]=d*-h+g*b;p[3]=a*-h+e*b},push:function(){w[t+0]=p[0];w[t+1]=p[1];w[t+2]=p[2];w[t+3]=
p[3];w[t+4]=p[4];w[t+5]=p[5];t+=6},pop:function(){t-=6;p[0]=w[t+0];p[1]=w[t+1];p[2]=w[t+2];p[3]=w[t+3];p[4]=w[t+4];p[5]=w[t+5]},img:function(b,d,a,g,e,h,l,c,f,m={x:1,y:1,z:1}){var n=d+g,D=a+e;e=a+e;g=d+g;var G=p[0],t=p[1],v=p[2],w=p[3],x=p[4],A=p[5],L=S.col;(b!=O||10922<=y+1)&&(q(34962,0,I),N(4,6*y,5123,0),y=0,O!=b&&F(3553,O=b));b=32*y;r[b++]=d*G+a*v+x;r[b++]=d*t+a*w+A;r[b++]=h;r[b++]=l;K[b++]=L;r[b++]=m.x;r[b++]=m.y;r[b++]=m.z;r[b++]=n*G+D*v+x;r[b++]=n*t+D*w+A;r[b++]=c;r[b++]=f;K[b++]=L;r[b++]=m.x;
r[b++]=m.y;r[b++]=m.z;r[b++]=d*G+e*v+x;r[b++]=d*t+e*w+A;r[b++]=h;r[b++]=f;K[b++]=L;r[b++]=m.x;r[b++]=m.y;r[b++]=m.z;r[b++]=g*G+a*v+x;r[b++]=g*t+a*w+A;r[b++]=c;r[b++]=l;K[b++]=L;r[b++]=m.x;r[b++]=m.y;r[b++]=m.z;10922<=++y&&(q(34962,0,I),N(4,6*y,5123,0),y=0)},flush:function(){0!=y&&(q(34962,0,r.subarray(0,32*y)),N(4,6*y,5123,0),y=0)}};return S}}(a.GL||(a.GL={}))}(H||(H={}));
(function(a){!function(c){c.TextureAtlasStore={};c.TextureStore={};c.load=function(f,e){let b=0,h=()=>{0>=--b&&e()};for(let d in f){let g=new Image;var l=f[d];g.onload="sWidth"in l&&"sHeight"in l?function(b,d,g){let e=f[b];return()=>{let h=a.GL.CreateTexture(a.Core._gl.gl,d,d.width,d.height),l=e.textures;c.TextureAtlasStore[b]=h;for(let b=0;b<l.length;b++)for(let a=0;a<l[b].length;a++)c.TextureStore[l[b][a]]={atlas:h,w:e.sWidth,h:e.sHeight,u0:a*e.sWidth/d.width,v0:b*e.sHeight/d.height,u1:(a*e.sWidth+
e.sWidth)/d.width,v1:(b*e.sHeight+e.sHeight)/d.height};g()}}(d,g,h):function(b,d,g){let e=f[b];return()=>{let h=a.GL.CreateTexture(a.Core._gl.gl,d,d.width,d.height),l=e.textures;c.TextureAtlasStore[b]=h;for(let b of l)c.TextureStore[b.name]={atlas:h,w:b.width,h:b.height,u0:b.x/d.width,v0:b.y/d.height,u1:(b.x+b.width)/d.width,v1:(b.y+b.height)/d.height};g()}}(d,g,h);b++;g.src=f[d].loc}}}(a.Assets||(a.Assets={}))})(H||(H={}));
(function(a){!function(c){function f(b,a,e,d){let g=[];var h=Math.abs(e-b),l=Math.abs(d-a),c=b,f=a,F=1+h+l;b=b<e?1:-1;a=a<d?1:-1;d=h-l;h*=2;for(l*=2;0<F;)g.push({x:c,y:f}),0<d?(c+=b,d-=l):(f+=a,d+=h),--F;return g}function e(b,a,e){let d=[],g=0,h=~~(1-e);for(;g<=e;)d.push({x:e+b,y:g+a}),d.push({x:g+b,y:e+a}),d.push({x:-e+b,y:g+a}),d.push({x:-g+b,y:e+a}),d.push({x:-e+b,y:-g+a}),d.push({x:-g+b,y:-e+a}),d.push({x:e+b,y:-g+a}),d.push({x:g+b,y:-e+a}),g+=1,h+=0>=h?2*g+1:2*(g- --e)+1;return d}c.calculateLight=
function(b,h){b.a=[];let c=e(b.position.x,b.position.y,b.radius);for(let d in c){let e=f(b.position.x,b.position.y,c[d].x,c[d].y),l=b.intensity/e.length,n=0;for(let d in e){if(0>e[d].x||e[d].x>=h.mapSize.x||0>e[d].y||e[d].y>=h.mapSize.y)break;let g=e[d].y*h.mapSize.x+e[d].x,c=l*(e.length-parseInt(d)),f=a.TileMap.getTile(h,{x:e[d].x,y:e[d].y});if(f.hasCollision&&0<n)break;if(g in b.a&&!(b.a[g]>c)||(b.a[g]=1<c?1:c),f.hasCollision)break;if(f.hasCollision&&1<n)break;if(f.hasCollision&&n++,!f)break}}};
c.calculateLightMap=function(b){let a=[];for(let e in b)for(let d in b[e].a)(!a[d]||a[d]>b[e].a[d])&&(a[d]=b[e].a[d]);return a};c.pointsOnLine=f;c.pointsOnCircle=e}(a.Lighting||(a.Lighting={}))})(H||(H={}));
(function(a){!function(a){!function(a){a.Position=class{constructor(b,a,e=!0){this.name=b;this.value=a;this.active=e}};a.Tag=class{constructor(b){this.value=this.name=b}};a.Flag=class{constructor(b,a){this.name=b;this.value=a}};a.Number=class{constructor(b,a){this.name=b;this.value=a}};a.Object=class{constructor(b,a){this.name=b;this.value=a}};a.coalesceValue=function(b,a){return null!=b?b.value:a}}(a.Component||(a.Component={}));class c{constructor(a){this._components={};this.id=c.__id++;this._manager=
a||null}SetManager(a){null!=this._manager&&this.DetachManager();this._manager=a;for(let b in this._components)this.registerComponentWithManager(this._components[b])}DetachManager(){for(let a in this._manager.collections){let b=this._manager.collections[a].indexOf(this);-1!==b&&this._manager.collections[a].splice(b,1)}this._manager=null}registerComponentWithManager(a){null==this._manager.collections[a.name]&&(this._manager.collections[a.name]=[]);this._manager.collections[a.name].push(this);this._manager.emit(this,
a.name,"added")}addComponent(a){return this._components[a.name]=a,null!=this._manager&&this.registerComponentWithManager(a),a}getComponent(a){return null==this._components[a]?null:this._components[a]}hasComponent(a){return null!=this._components[a]}}c.__id=1;a.Entity=c;a.Manager=class{constructor(){this.collections={};this._eventHandlers={};this.entities=[]}reset(){this.collections={};this._eventHandlers={};this.entities.length=0}addEntity(a){return null==a?a=new c(this):a.SetManager(this),this.entities[a.id]=
a,a}getAll(a){return this.collections[a]?this.collections[a]:[]}getFirst(a){return null==this.collections[a]?null:this.collections[a][0]}on(a,b,h){null==this._eventHandlers[a]&&(this._eventHandlers[a]={});null==this._eventHandlers[a][b]&&(this._eventHandlers[a][b]=[]);this._eventHandlers[a][b].push(h)}emit(a,b,h){this._eventHandlers[b]&&this._eventHandlers[b][h]&&this._eventHandlers[b][h].forEach((e)=>{e(a,this.collections[b],h)})}}}(a.ECS||(a.ECS={}))})(H||(H={}));
(function(a){a.TileStorage={};a.TileNames={};(function(c){let f;!function(a){a.draw=function(b,a,e,d,g){c.Texture.draw({renderer:b,texture:e,position:{x:d*e.w-a.position.x,y:g*e.h-a.position.y}})}}(f=c.Tile||(c.Tile={}));(function(e){e.draw=function(b,e,c){let d=B(e.position,c.tileSize),g=B(e.size,c.tileSize);for(let h=d.x;h<=d.x+g.x;h++)for(let l=d.y;l<=d.y+g.y;l++){let d=a.TileMap.getTile(c,{x:h,y:l});null!=d&&(b.col=d.colour,f.draw(b,e,d.texture,h,l))}}})(c.TileMap||(c.TileMap={}))})(a.Graphics||
(a.Graphics={}));(function(c){function f(){return e.next().value}let e=function*(){let b=0;for(;;)yield b++}();c.NextTileId=f;c.CreateAndStore=function(b,e,c,d){e={id:f(),texture:e,colour:c,hasCollision:d};return a.TileStorage[b]=e,a.TileNames[e.id]=b,e}})(a.Tile||(a.Tile={}));(function(c){let f=[];c.addTile=function(a,b,c){c=c.x+c.y*a.mapSize.x;void 0===a.tiles[c]&&(a.tiles[c]=0);a.tiles[c]|=b.hasCollision?1:0;a.tiles[c]|=b.id<<1};c.getTile=function(e,b){return b.x>=e.mapSize.x||b.y>=e.mapSize.y||
0>b.x||0>b.y?null:a.TileStorage[a.TileNames[(255&e.tiles[b.x+b.y*e.mapSize.x])>>1]]};c.getEntities=function(a,b){let e=[];for(a=f[(-133169153&a.tiles[b.x+b.y*a.mapSize.x])>>12];a;)e.push(a.ecs),a=a.next;return e};c.mapEntity=function(a,b,c){let e=f[a.id]||{next:null,ecs:a,position:c,previous:null};if(null!=f[a.id]){var d=e.position.x+e.position.y*b.mapSize.x;(-133169153&b.tiles[d])>>12==e.ecs.id&&(b.tiles[d]&=-16773121,e.next&&(b.tiles[d]|=e.next.ecs.id<<12));e.next&&(e.next.previous=e.previous);
e.previous&&(e.previous.next=e.next);e.next=e.previous=null}d=c.x+c.y*b.mapSize.x;var g=(-133169153&b.tiles[d])>>12;0!==g&&(b.tiles[d]&=-16773121,g=f[g],e.next=g,g.previous=e);e.position=u(c);b.tiles[d]|=a.id<<12;f[a.id]=e}})(a.TileMap||(a.TileMap={}))})(H||(H={}));
(function(a){!function(a){function c(a,b){b=a.interpolator.next(b);let e=a.origin,c=a.target;a.position.x=e.x+Math.round((c.x-e.x)*b.value);a.position.y=e.y+Math.round((c.y-e.y)*b.value);1==b.done&&(a.moving=!1,a.position=u(a.target),a.origin=u(a.target),a.interpolator=null)}a.create=function(a,b){return{position:a,origin:a,target:a,size:b,moving:!1,interpolator:null}};a.update=function(a,b){a.moving&&c(a,b)};a.move=function(a,b,c,f=0,d=(a)=>a){a.target=u(b);a.origin=u(a.position);a.interpolator=
M(c,f,d);a.moving=!0};a.interpolate=c}(a.Camera||(a.Camera={}))})(H||(H={}));
(function(a){!function(c){let f,e;c.SpriteStore={};c.NinePatchStore={};(function(a){function b(a){return Object.assign({},a)}a.clone=b;a.cloneArray=function(a){let d=[];return a.forEach((a)=>{d.push(b(a))}),d}})(f||(f={}));class b{constructor(a){this.animations={};this.animationQueue=[];this.animations.DEFAULT=a;this.play("DEFAULT")}clone(){let a=new b(this.animations.DEFAULT.clone());for(let b in this.animations)a.addAnimation(b,this.animations[b].clone());return a}get currentAnimation(){return this.animationQueue[0]}get currentFrame(){return this.currentAnimation.currentFrame}addAnimation(a,
b){this.animations[a]=b}play(a,b=!1){this.animationQueue.length=0;a=this.animations[a].clone();return a.loop=b,this.animationQueue.push(a),this}then(a,b=!1){a=this.animations[a].clone();return a.loop=b,this.animationQueue.push(a),this}next(){this.animationQueue.shift();0===this.animationQueue.length&&this.stop()}stop(){this.animationQueue.length=0;this.animationQueue.push(this.animations.DEFAULT)}update(a,b){this.currentAnimation.done&&this.next();this.currentAnimation.update(b)}setColour(a){for(let b in this.animations)this.animations[b].setColour(a);
this.animationQueue.forEach((b)=>{b.setColour(a)})}setRotation(a){for(let b in this.animations)this.animations[b].setRotation(a);this.animationQueue.forEach((b)=>{b.setRotation(a)})}}c.Sprite=b;(function(b){class h{constructor(a){this._duration=-1;this.progress=0;this.done=this.loop=!1;this.frames=a}get currentFrame(){if(0===this.duration)return this.frames[0];{let a=0;for(let b in this.frames)if(a+=this.frames[b].duration,this.progress<=a)return this.frames[b];return this.frames[this.frames.length-
1]}}get duration(){if(-1===this._duration){this._duration=0;for(let a of this.frames)this._duration+=a.duration}return this._duration}clone(){return new h(f.cloneArray(this.frames))}update(a){if(this.done=!1,0===this.duration)return this.frames[0];this.progress+=a;this.progress>this.duration&&(this.loop?this.progress=0:(this.progress=0,this.done=!0))}setColour(a){this.frames.forEach((b)=>{b.colour=a})}setRotation(a){this.frames.forEach((b)=>{b.rotation=a})}}b.Animation=h;b.draw=function(a,b,c,f={x:0,
y:0}){a.col=b.currentFrame.colour;e.draw({renderer:a,texture:b.currentFrame.texture,position:k.sub(c,f),rotation:b.currentFrame.rotation})};b.CreateAndStore=function(d){let g=new b(new b.Animation([{texture:a.Assets.TextureStore[d.animations.DEFAULT[0].texture],colour:d.animations.DEFAULT[0].colour||4294967295,duration:d.animations.DEFAULT[0].duration}]));for(let c in d.animations){let e=d.animations[c],f=[];for(let b of e)f.push({texture:a.Assets.TextureStore[b.texture],colour:b.colour||4294967295,
duration:b.duration});g.addAnimation(c,new b.Animation(f))}return c.SpriteStore[d.name]=g,g}})(b=c.Sprite||(c.Sprite={}));(function(a){a.draw=function(a,b,c,f,h,q){h=c+h-1;let d=f+q-1;for(let g=c;g<=h;g++)for(let l=f;l<=d;l++)q=g===c?l===f?b.tl:l===d?b.bl:b.ml:g===h?l===f?b.tr:l===d?b.br:b.mr:l===f?b.tc:l===d?b.bc:b.mc,e.draw({renderer:a,texture:q,position:{x:g*q.w,y:l*q.h}})}})(c.NinePatch||(c.NinePatch={}));(function(a){a.draw=function(a){let b=a.texture,c=b.w,e=~~(c/2),f=b.h,h=~~(f/2),l=a.renderer,
F=a.light?a.light:{x:1,y:1,z:1},D=a.position;l.push();l.trans(D.x+e,D.y+h);a.scale&&l.scale(a.scale.x,a.scale.y);a.rotation&&l.rot(a.rotation);l.img(b.atlas,-e,-h,c,f,b.u0,b.v0,b.u1,b.v1,F);l.pop()}})(e=c.Texture||(c.Texture={}));(function(b){let c;!function(a){a[a.LEFT=0]="LEFT";a[a.CENTER=1]="CENTER";a[a.RIGHT=2]="RIGHT"}(c=b.Alignment||(b.Alignment={}));b.draw=function(b,e,f,h=c.LEFT,l=0){f=u(f);let d=e.split(" "),g=f.x,m=0,n=0==l?6*e.split("").length:l;e=0;h==c.CENTER?e=~~(-n/2):h===c.RIGHT&&
(e=~~-n);for(let c of d){0!=l&&m+6*c.length>l&&(f.y+=6,m=0);for(let d of c.split(""))h=d.toLowerCase(),h=a.Assets.TextureStore[h],f.x=g+m,b.push(),b.trans(f.x,f.y),b.img(h.atlas,e,0,h.w,h.h,h.u0,h.v0,h.u1,h.v1),b.pop(),m+=6;m+=6}}})(c.Text||(c.Text={}))}(a.Graphics||(a.Graphics={}))})(H||(H={}));
(function(a){!function(a){a.Manager=class{constructor(){this.subscribers={}}reset(){this.subscribers={}}};a.emit=function(a,c,b,...h){a.subscribers[c]&&a.subscribers[c][b]&&a.subscribers[c][b].forEach((a)=>{a(...h)})};a.on=function(a,c,b,h){null==a.subscribers[c]&&(a.subscribers[c]={});null==a.subscribers[c][b]&&(a.subscribers[c][b]=[]);a.subscribers[c][b].push(h)}}(a.Events||(a.Events={}))})(H||(H={}));
(function(a){var c=a.Graphics;a.Scene=class{constructor(f){this.ecsManager=new a.ECS.Manager;this.eventManager=new a.Events.Manager;this.subSceneManager=new a.StateMachine;this._storage={};this.transitionIn=f.transitionIn;this.transitionOut=()=>{this._storage={};this.ecsManager.reset();this.eventManager.reset();this.subSceneManager.reset();f.transitionOut()};this.update=f.update;this.render=(e,b,h)=>{let l=a.Camera.current;e.bkg(0,0,0);e.col=4294967295;this.ecsManager.getAll("renderable").forEach((a)=>
{if(a.hasComponent("tileMap"))a=a.getComponent("tileMap").value,c.TileMap.draw(e,l,a);else if(a.hasComponent("sprite")){var b=a.getComponent("sprite").value;a=a.getComponent("renderPos").value;c.Sprite.draw(e,b,a,l.position)}else a.hasComponent("text")?(b=a.getComponent("text").value,a=a.getComponent("renderPos").value,e.col=b.colour,c.Text.draw(e,b.text,a,b.textAlign,b.wrapWidth)):a.hasComponent("9patch")&&(b=a.getComponent("9patch").value,a=a.getComponent("tilePos").value,e.col=b.colour,c.NinePatch.draw(e,
c.NinePatchStore[b.name],a.x,a.y,b.tileSize.x,b.tileSize.y))});f.render(e,b,h);this.subSceneManager.current&&this.subSceneManager.current.render(e,b,h)};this.name=f.name}attach(a,c){return this._storage[a]=c,c}modify(a,c){return this._storage[a]=c,c}fetch(a){return this._storage[a]}}})(H||(H={}));
(function(a){!function(a){function c(a){d||(a=a.which,l[a]&&b[a]&&b[a].keyDown(),l[a]=!1,h[a]=!0)}function e(a){d||(a=a.which,b[a]&&b[a].keyUp(),h[a]=!1,l[a]=!0)}a.Controls={};let b=[],h=[],l=[],d=!1;for(let a=0;256>a;a++)l[a]=!0;window.onkeydown=c;window.onkeyup=e;a.keyDown=c;a.keyUp=e;a.disable=function(){d=!0;h.forEach((a,d,c)=>{a&&b[d].keyUp();c[d]=!1});l.forEach((a,b,d)=>{d[b]=!0})};a.enable=function(){d=!1};a.bindKey=function(a,d,c=()=>{}){b[a]={keyDown:d,keyUp:c}};a.unbindKey=function(a){delete b[a]};
a.unbindAll=function(){for(let a in b)delete b[a]};a.bindControl=function(d,c,e=()=>{}){for(let g of a.Controls[d])b[g]={keyDown:c,keyUp:e}};a.unbindControl=function(d){for(let c of a.Controls[d])delete b[c]}}(a.Input||(a.Input={}))})(H||(H={}));
(function(a){!function(c){function f(e){if(g){let g=e-h;h=e;d||function(a,d){let c=b.current;c&&c.update(a,d)}(e,g);(function(e,g){let f=b.current;(c._gl.cls(),d)?(e=~~(c.WIDTH/2),g=~~(c.HEIGHT/2),c._gl.col=4294967295,a.Graphics.Text.draw(c._gl,"game paused",{x:e,y:g-8},a.Graphics.Text.Alignment.CENTER),a.Graphics.Text.draw(c._gl,"click here to resume",{x:e,y:g+8},a.Graphics.Text.Alignment.CENTER)):f&&f.render(c._gl,e,g);c._gl.flush()})(e,g);requestAnimationFrame(f)}}let e,b,h,l;c.WIDTH=0;c.HEIGHT=
0;c.addScene=function(a){b.register(a)};c.pushScene=function(a,...d){b.push(a,...d)};c.popScene=function(){b.pop()};let d=!1,g=!1;c.init=function(d){e=d;c._gl=a.GL.Renderer(e);a.Camera.current=a.Camera.create({x:0,y:0},{x:c.WIDTH,y:c.HEIGHT});b=new a.StateMachine;c.WIDTH=c._gl.canvas.width;c.HEIGHT=c._gl.canvas.height};c.start=function(){h=performance.now();c._gl.bkg(0,0,0);g=!0;l=requestAnimationFrame(f)};c.stop=function(){g=!1;cancelAnimationFrame(l)};c.pause=function(){d=!0;a.Input.disable()};
c.unpause=function(){d=!1;a.Input.enable()}}(a.Core||(a.Core={}))})(H||(H={}));(function(a){var c=null;a.setStorage=function(a){c=a};a.newGame=function(){T.gameState={version:"0.0.0",wallPoints:0,towerPoints:0,upgradePoint:0}};a.save=function(){c.setItem("save",JSON.stringify(T.gameState))};a.saveExists=function(){var a=c.getItem("save");return null!=a&&""!=a};a.load=function(){var a=c.getItem("save");T.gameState=JSON.parse(a)}})(P||(P={}));
(function(a){var c=H,f=c.Core,e=c.Input,b=c.Graphics,h=H.ECS.Component;a.TitleMenu=new c.Scene({name:"TitleMenu",transitionIn(){let a=this,d=0,c=[];c=P.saveExists()?["Continue","New Game","Settings"]:["New Game","Settings"];a.attach("menuOptions",c);let m=~~(f.HEIGHT/2),n=a.ecsManager;var q=n.addEntity();q.addComponent(new h.Position("tilePos",{x:0,y:0}));q.addComponent(new h.Object("9patch",{name:"dialog",colour:4294901760,tileSize:{x:32,y:18}}));q.addComponent(new h.Number("sort",0));q.addComponent(new h.Tag("renderable"));
q=n.addEntity();q.addComponent(new h.Position("renderPos",{x:16,y:16}));q.addComponent(new h.Object("text",{text:"Tower Defense",textAlign:b.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295}));q.addComponent(new h.Number("sort",10));q.addComponent(new h.Tag("renderable"));c.forEach((c,e)=>{let g=n.addEntity();g.addComponent(new h.Position("renderPos",{x:32,y:m+16*e}));let f=c;d===e&&(f=`(${f})`);let l=g.addComponent(new h.Object("text",{text:f,textAlign:b.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295}));
g.addComponent(new h.Number("sort",10));g.addComponent(new h.Tag("renderable"));H.Events.on(a.eventManager,"sel","change",(a)=>{l.value.text=e==a?`(${c})`:c})});e.bindControl("DOWN",()=>{(d+=1)>c.length-1&&(d=0);H.Events.emit(a.eventManager,"sel","change",d)});e.bindControl("UP",()=>{0>--d&&(d=c.length-1);H.Events.emit(a.eventManager,"sel","change",d)});e.bindControl("ACTION",()=>{switch(c[d]){case "Continue":P.load();f.pushScene("Game");break;case "New Game":P.newGame();f.pushScene("Game");break;
case "Settings":f.pushScene("SettingsMenu")}})},transitionOut(){e.unbindAll()},update(){},render(){}})})(R||(R={}));
(function(a){a.handlePlayerInput=function(a){let c=a.getComponent("tilePos"),b=a.getComponent("targetTile"),f=a.getComponent("moving"),l=a.getComponent("movingRight"),d=a.getComponent("movingLeft"),g=a.getComponent("movingUp");a=a.getComponent("movingDown");0==f.value&&(l.value&&b.value.x++,d.value&&b.value.x--,g.value&&b.value.y--,a.value&&b.value.y++,c.value.x==b.value.x&&c.value.y==b.value.y||(f.value=!0))};a.handleCollision=function(a,c){let b=a.getComponent("tilePos"),e=a.getComponent("targetTile"),
f=a.getComponent("moving"),d=a.getComponent("movingRight"),g=a.getComponent("movingLeft"),m=a.getComponent("movingUp");a=a.getComponent("movingDown");if(d.value||g.value){let a=H.TileMap.getTile(c,{x:e.value.x,y:b.value.y});a&&a.hasCollision&&(d.value=g.value=!1,e.value.x=b.value.x)}(m.value||a.value)&&(c=H.TileMap.getTile(c,{x:b.value.x,y:e.value.y}))&&c.hasCollision&&(m.value=a.value=!1,e.value.y=b.value.y);b.value.x===e.value.x&&b.value.y===e.value.y&&(f.value=!1)};let c={};a.moveEntity=function(a,
e,b){let f=a.getComponent("tilePos"),l=a.getComponent("targetTile"),d=a.getComponent("renderPos"),g=a.getComponent("moving");null==c[a.id]&&(c[a.id]={});null==c[a.id].moveFn&&(c[a.id].moveFn=M(b,160,J.linear));b=c[a.id].moveFn.next(b);let m=z(f.value,e.tileSize),n=z(l.value,e.tileSize);d.value.x=m.x+Math.round((n.x-m.x)*b.value);d.value.y=m.y+Math.round((n.y-m.y)*b.value);1==b.done&&(g.value=!1,f.value=u(l.value),d.value=z(f.value,e.tileSize),H.TileMap.mapEntity(a,e,f.value),delete c[a.id].moveFn)}})(Q||
(Q={}));
(function(a){!function(a){!function(a){var c=H.Input,b=H.ECS.Component,f=H.Graphics;a.Move=new H.Scene({name:"Move",transitionIn(a){this.attach("parentScene",a);var d=a.ecsManager;let e=d.getFirst("player"),h=d.getFirst("levelMap").getComponent("tileMap").value;d=this.ecsManager.addEntity();d.addComponent(new b.Position("renderPos",{x:448,y:8}));d.addComponent(new b.Object("text",{text:"Move Mode",textAlign:f.Text.Alignment.CENTER,wrapWidth:0,colour:4294967295}));d.addComponent(new b.Number("sort",10));
d.addComponent(new b.Tag("renderable"));d=this.ecsManager.addEntity();d.addComponent(new b.Position("renderPos",{x:392,y:H.Core.HEIGHT-16}));d.addComponent(new b.Object("text",{text:"Space: Build",textAlign:f.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295}));d.addComponent(new b.Number("sort",10));d.addComponent(new b.Tag("renderable"));c.bindControl("RIGHT",()=>{e.getComponent("movingRight").value=!0},()=>{e.getComponent("movingRight").value=!1});c.bindControl("LEFT",()=>{e.getComponent("movingLeft").value=
!0},()=>{e.getComponent("movingLeft").value=!1});c.bindControl("DOWN",()=>{e.getComponent("movingDown").value=!0},()=>{e.getComponent("movingDown").value=!1});c.bindControl("UP",()=>{e.getComponent("movingUp").value=!0},()=>{e.getComponent("movingUp").value=!1});c.bindControl("ACTION",()=>{},()=>{let b=e.getComponent("tilePos").value;0===H.TileMap.getEntities(h,b).filter((a)=>a.hasComponent("blocking")).length&&a.subSceneManager.push("Build",a)})},transitionOut(){c.unbindAll()},update(){},render(){}})}(a.SubScenes||
(a.SubScenes={}))}(a.Game||(a.Game={}))})(R||(R={}));
(function(a){!function(a){!function(a){var c=H.Input,b=H.ECS.Component,f=H.Graphics;a.Build=new H.Scene({name:"Build",transitionIn(a){this.attach("parentScene",a);var d=this.ecsManager,e=d.addEntity();e.addComponent(new b.Position("renderPos",{x:448,y:8}));e.addComponent(new b.Object("text",{text:"Build Mode",textAlign:f.Text.Alignment.CENTER,wrapWidth:0,colour:4294967295}));e.addComponent(new b.Number("sort",10));e.addComponent(new b.Tag("renderable"));e=d.addEntity();e.addComponent(new b.Position("renderPos",
{x:392,y:H.Core.HEIGHT-16}));e.addComponent(new b.Object("text",{text:"Esc: Back",textAlign:f.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295}));e.addComponent(new b.Number("sort",10));e.addComponent(new b.Tag("renderable"));d=d.addEntity();d.addComponent(new b.Position("renderPos",{x:392,y:H.Core.HEIGHT-24}));d.addComponent(new b.Object("text",{text:"Space: Confirm",textAlign:f.Text.Alignment.LEFT,wrapWidth:0,colour:4294967295}));d.addComponent(new b.Number("sort",10));d.addComponent(new b.Tag("renderable"));
c.bindControl("BACK",()=>{},()=>{a.subSceneManager.pop(a)})},transitionOut(){c.unbindAll()},update(){},render(){}})}(a.SubScenes||(a.SubScenes={}))}(a.Game||(a.Game={}))})(R||(R={}));(function(a){!function(a){!function(a){a.Defend=new H.Scene({name:"Defend",transitionIn(a){this.attach("parentScene",a)},transitionOut(){},update(){},render(){}})}(a.SubScenes||(a.SubScenes={}))}(a.Game||(a.Game={}))})(R||(R={}));
(function(a){!function(a){var c=H,e=c.ECS,b=e.Component,h=c.Graphics;a.scene=new c.Scene({name:"Game",transitionIn(){let f=this.ecsManager;f.on("renderable","added",(a,b)=>{b.sort((a,b)=>e.Component.coalesceValue(a.getComponent("sort"),0)-e.Component.coalesceValue(b.getComponent("sort"),0))});let d={mapSize:{x:24,y:24},tileSize:16,tiles:[]};this.attach("cameraGap",6*d.tileSize);H.Camera.current=H.Camera.create({x:0,y:0},{x:24*d.tileSize,y:18*d.tileSize});(function(a){for(let b=0;b<a.mapSize.x;b++)for(let c=
0;c<a.mapSize.y;c++)b===a.mapSize.x-1||0===b||c===a.mapSize.y-1?H.TileMap.addTile(a,H.TileStorage.wall,{x:b,y:c}):0===c?H.TileMap.addTile(a,H.TileStorage.north_wall,{x:b,y:c}):H.TileMap.addTile(a,H.TileStorage.floor,{x:b,y:c})})(d);var g=f.addEntity();g.addComponent(new b.Tag("levelMap"));g.addComponent(new b.Object("tileMap",d));g.addComponent(new b.Number("sort",1));g.addComponent(new b.Tag("renderable"));g=f.addEntity();g.addComponent(new b.Position("tilePos",{x:24,y:0}));g.addComponent(new b.Object("9patch",
{name:"dialog",colour:4294936712,tileSize:{x:8,y:18}}));g.addComponent(new b.Number("sort",9));g.addComponent(new b.Tag("renderable"));g=f.addEntity();g.addComponent(new b.Tag("player"));var m=g.addComponent(new b.Position("tilePos",{x:1,y:1}));g.addComponent(new b.Position("renderPos",z(m.value,d.tileSize)));g.addComponent(new b.Position("targetTile",u(m.value)));g.addComponent(new b.Flag("moving",!1));g.addComponent(new b.Flag("movingLeft",!1));g.addComponent(new b.Flag("movingRight",!1));g.addComponent(new b.Flag("movingUp",
!1));g.addComponent(new b.Flag("movingDown",!1));var n=h.SpriteStore.cursor.clone();n.play("blink",!0);n.setColour(4278255360);g.addComponent(new b.Object("sprite",n));g.addComponent(new b.Number("sort",2));g.addComponent(new b.Tag("renderable"));c.TileMap.mapEntity(g,d,m.value);g=f.addEntity();g.addComponent(new b.Tag("blocking"));m=g.addComponent(new b.Position("tilePos",{x:1,y:1}));g.addComponent(new b.Position("renderPos",z(m.value,d.tileSize)));g.addComponent(new b.Position("targetTile",u(m.value)));
n=h.SpriteStore.spawner.clone();n.setColour(4278190335);g.addComponent(new b.Object("sprite",n));g.addComponent(new b.Number("sort",2));g.addComponent(new b.Tag("renderable"));c.TileMap.mapEntity(g,d,m.value);for(g=0;10>g;g++){m=f.addEntity();n=m.addComponent(new b.Position("tilePos",{x:-2,y:g+1}));m.addComponent(new b.Position("renderPos",z(n.value,d.tileSize)));{n=h.SpriteStore.cursor.clone();let a=E(C(50,255),C(50,255),C(50,255),C(175,255));0==g%2?n.play("blink",!0):n.play("quick-blink",!0);n.setColour(a);
m.addComponent(new b.Object("sprite",n))}m.addComponent(new b.Number("sort",3));m.addComponent(new b.Tag("renderable"))}for(g=0;10>g;g++)m=f.addEntity(),n=m.addComponent(new b.Position("tilePos",{x:1,y:g+2})),m.addComponent(new b.Position("renderPos",z(n.value,d.tileSize))),n=h.SpriteStore.arrow.clone(),n.setRotation(Math.PI),n.play("blink",!0),m.addComponent(new b.Object("sprite",n)),m.addComponent(new b.Number("sort",4)),m.addComponent(new b.Tag("renderable"));for(g=0;10>g;g++)m=f.addEntity(),n=
m.addComponent(new b.Position("tilePos",{x:g+2,y:g+2})),m.addComponent(new b.Position("renderPos",z(n.value,d.tileSize))),n=h.SpriteStore.arrow_diag.clone(),n.setRotation(Math.PI),n.play("blink",!0),m.addComponent(new b.Object("sprite",n)),m.addComponent(new b.Number("sort",4)),m.addComponent(new b.Tag("renderable"));this.subSceneManager.register(a.SubScenes.Move);this.subSceneManager.register(a.SubScenes.Build);this.subSceneManager.register(a.SubScenes.Defend);this.subSceneManager.push("Move",this)},
transitionOut(){},update(a,b){var c=this.ecsManager,d=c.getFirst("player"),e=c.getFirst("levelMap").getComponent("tileMap").value;let f=H.Camera.current,h=this.fetch("cameraGap");Q.handlePlayerInput(d);c.getAll("sprite").forEach((c)=>{c.getComponent("sprite").value.update(a,b)});c=d.getComponent("moving");(c.value&&(Q.handleCollision(d,e),c.value&&Q.moveEntity(d,e,a)),f.moving)||(d=d.getComponent("renderPos").value,e=d.x-(f.position.x+~~(f.size.x/2)),c=d.y-(f.position.y+~~(f.size.y/2)),(e>=h||e<=
-h||c>=h||c<=-h)&&H.Camera.move(f,{x:d.x-~~(f.size.x/2),y:d.y-~~(f.size.y/2)},a,1500,J.outQuart));H.Camera.update(f,a)},render(){}})}(a.Game||(a.Game={}))})(R||(R={}));
(function(a){var c=H.Core,f=H.Input,e=H.Graphics,b=H.ECS.Component;a.SettingsMenu=new H.Scene({name:"SettingsMenu",transitionIn(){let a=this,l=0,d=["Back"],g=~~(c.HEIGHT/2),m=~~(c.WIDTH/2),n=a.ecsManager;var q=n.addEntity();q.addComponent(new b.Position("tilePos",{x:0,y:0}));q.addComponent(new b.Object("9patch",{name:"dialog",colour:4294901760,tileSize:{x:32,y:18}}));q.addComponent(new b.Number("sort",0));q.addComponent(new b.Tag("renderable"));q=n.addEntity();q.addComponent(new b.Position("renderPos",
{x:m,y:16}));q.addComponent(new b.Object("text",{text:"Settings",textAlign:e.Text.Alignment.CENTER,wrapWidth:0,colour:4294967295}));q.addComponent(new b.Number("sort",10));q.addComponent(new b.Tag("renderable"));d.forEach((c,d)=>{let f=n.addEntity();f.addComponent(new b.Position("renderPos",{x:m,y:g+16*d}));let h=c;l===d&&(h=`(${h})`);let q=f.addComponent(new b.Object("text",{text:h,textAlign:e.Text.Alignment.CENTER,wrapWidth:0,colour:4294967295}));f.addComponent(new b.Number("sort",10));f.addComponent(new b.Tag("renderable"));
H.Events.on(a.eventManager,"sel","change",(a)=>{q.value.text=d==a?`(${c})`:c})});f.bindControl("DOWN",()=>{(l+=1)>d.length-1&&(l=0);H.Events.emit(a.eventManager,"sel","change",l)});f.bindControl("UP",()=>{0>--l&&(l=d.length-1);H.Events.emit(a.eventManager,"sel","change",l)});f.bindControl("ACTION",()=>{switch(d[l]){case "Back":c.popScene()}})},transitionOut(){f.unbindAll()},update(){},render(){}})})(R||(R={}));
(function(a){var c=H,f=c.Core,e=c.Input,b=c.Graphics;a.PostGame=new c.Scene({name:"PostGame",transitionIn(){e.bindControl("ACTION",()=>{f.popScene();f.popScene()})},transitionOut(){e.unbindControl("ACTION")},update(){},render(a){a.col=4292682274;b.NinePatch.draw(a,b.NinePatchStore.dialog,0,0,32,18);a.col=4294967295;b.Text.draw(a,"Winner is you.",{x:~~(f.WIDTH/2),y:~~(f.HEIGHT/2)},b.Text.Alignment.CENTER)}})})(R||(R={}));
(function(a){var c=H.Core,f=H.Graphics,e=H.Assets;let b=[{name:"cursor",animations:{DEFAULT:[{texture:"cursor",duration:0}],blink:[{texture:"cursor_light",duration:250},{texture:"cursor",duration:250},{texture:"cursor_dark",duration:250},{texture:"cursor",duration:250}],"quick-blink":[{texture:"cursor_light",duration:150},{texture:"cursor",duration:150},{texture:"cursor_dark",duration:150},{texture:"cursor",duration:150}]}},{name:"spawner",animations:{DEFAULT:[{texture:"spawner",duration:0}]}},{name:"arrow",
animations:{DEFAULT:[{texture:"arrow_cart",duration:0}],blink:[{texture:"arrow_cart",colour:3710001919,duration:350},{texture:"arrow_cart",colour:2569151231,duration:350},{texture:"arrow_cart",colour:1428300543,duration:350},{texture:"arrow_cart",colour:2569151231,duration:350}]}},{name:"arrow_diag",animations:{DEFAULT:[{texture:"arrow_diag",duration:0}],blink:[{texture:"arrow_diag",colour:2283938559,duration:350},{texture:"arrow_diag",colour:1713513215,duration:350},{texture:"arrow_diag",colour:1143087871,
duration:350},{texture:"arrow_diag",colour:1713513215,duration:350}]}}];a.gameState=null;a.setup=function(){c.addScene(R.TitleMenu);c.addScene(R.SettingsMenu);c.addScene(R.Game.scene);c.addScene(R.PostGame);for(let a of b)f.Sprite.CreateAndStore(a);H.Tile.CreateAndStore("north_wall",e.TextureStore.brick,4281150765,!0);H.Tile.CreateAndStore("wall",e.TextureStore.brick,4281150765,!0);H.Tile.CreateAndStore("floor",e.TextureStore.brick,4278519045,!1);f.NinePatchStore.dialog={tl:e.TextureStore.dialog_tl,
tc:e.TextureStore.dialog_t,tr:e.TextureStore.dialog_tr,ml:e.TextureStore.dialog_ml,mc:e.TextureStore.dialog_m,mr:e.TextureStore.dialog_mr,bl:e.TextureStore.dialog_bl,bc:e.TextureStore.dialog_b,br:e.TextureStore.dialog_br};c.pushScene("TitleMenu")}})(T||(T={}));
(function(a){var c=H.Core,f=H.Input,e=H.Assets;let b={alpha:{loc:"res/alpha.png",sWidth:5,sHeight:5,textures:["abcdefghijklmnopqrstuvwxyz".split(""),"1234567890.!?#()-^+\x3d/\\:,'\"".split("")]},tiles:{loc:"res/test.png",sWidth:16,sHeight:16,textures:[["brick","cursor","cursor_dark","cursor_light"],["dialog_tl","dialog_t","dialog_tr","arrow_cart"],["dialog_ml","dialog_m","dialog_mr","arrow_diag"],["dialog_bl","dialog_b","dialog_br","spawner"]]},irreg:{loc:"res/irreg.png",textures:[{name:"test",x:0,
y:0,width:32,height:32}]}};a.onload=function(){function h(){var a=c._gl.canvas,b=0|Math.min(window.innerWidth/a.width,window.innerHeight/a.height);b=0>=b?1:b;a=[a.width*b,a.height*b];a=[(window.innerWidth-a[0])/2,(window.innerHeight-a[1])/2];b="translate("+~~a[0]+"px, "+~~a[1]+"px) scale("+~~b+")";a=document.getElementById("stage");a.style.transform=b;a.style.webkitTransform=b}c.init(document.getElementById("canvas"));P.setStorage(window.localStorage);f.Controls.UP=[38,87];f.Controls.DOWN=[40,83];
f.Controls.LEFT=[37,65];f.Controls.RIGHT=[39,68];f.Controls.ACTION=[13,32];f.Controls.BACK=[27];e.load(b,()=>{window.onresize=h;h();window.onblur=()=>{c.pause()};window.onfocus=()=>{c.unpause()};c.start();a.setup()})}})(T||(T={}));window.onload=T.onload;
})()