(function(){
'use strict';var l;function r(a){return{x:a.x,y:a.y}}function A(a,c){return{x:a.x*c,y:a.y*c}}function C(a,c){return{x:~~(a.x/c),y:~~(a.y/c)}}function D(a,c){return Math.floor(Math.random()*(c-a+1))+a}function F(a,c,e,d){return((((0|255&d)<<8>>>0|255&e)<<8>>>0|255&c)<<8>>>0|255&a)>>>0}
!function(a){a.StateMachine=class{constructor(){this._stateDictionary={};this._stateStack=[]}register(c){this._stateDictionary[c.name]=c}get current(){return this._stateStack[this._stateStack.length-1]}push(c,...a){this.current&&this.current.transitionOut&&this.current.transitionOut();(c=this._stateDictionary[c])&&c.transitionIn&&c.transitionIn(...a);this._stateStack.push(c)}pop(...a){if(this.current&&this.current.transitionOut&&this.current.transitionOut(),2>this._stateStack.length)return null;var c=
this._stateStack[this._stateStack.length-2];return c&&c.transitionIn&&c.transitionIn(...a),this._stateStack.pop()}}}(G||(G={}));(function(a){a.add=function(a,e){return{x:a.x+e.x,y:a.y+e.y}};a.sub=function(a,e){return{x:a.x-e.x,y:a.y-e.y}}})(l||(l={}));
const J={linear:function(a){return a},inQuad:function(a){return a*a},outQuad:function(a){return a*(2-a)},inOutQuad:function(a){return.5>a?2*a*a:(4-2*a)*a-1},inCubic:function(a){return a*a*a},outCubic:function(a){return--a*a*a+1},inOutCubic:function(a){return.5>a?4*a*a*a:(a-1)*(2*a-2)*(2*a-2)+1},inQuart:function(a){return a*a*a*a},outQuart:function(a){return 1- --a*a*a*a},inOutQuart:function(a){return.5>a?8*a*a*a*a:1-8*--a*a*a*a},inQuint:function(a){return a*a*a*a*a},outQuint:function(a){return 1+
--a*a*a*a*a},inOutQuint:function(a){return.5>a?16*a*a*a*a*a:1+16*--a*a*a*a*a}};function*N(a,c,e){let d;for(d=yield 0;d-a<c;)d=yield e((d-a)/c);if(d-a>=c)return 1}var P,G,Q,R,T;
!function(a){!function(a){function c(b,a,c){c=b.createShader(c);return b.shaderSource(c,a),b.compileShader(c),c}function d(b,a,d){var h=b.createProgram();a=c(b,a,35633);d=c(b,d,35632);return b.attachShader(h,a),b.attachShader(h,d),b.linkProgram(h),h}function b(b,a,c,d){var h=b.createBuffer();return b.bindBuffer(a,h),b.bufferData(a,c,d),h}a.CompileShader=c;a.CreateShaderProgram=d;a.CreateBuffer=b;a.CreateTexture=function(b,a){var c=b.createTexture();return b.bindTexture(3553,c),b.texParameteri(3553,
10242,33071),b.texParameteri(3553,10243,33071),b.texParameteri(3553,10240,9728),b.texParameteri(3553,10241,9728),b.texImage2D(3553,0,6408,6408,5121,a),b.bindTexture(3553,null),c};a.Renderer=function(a){var c,g=a.getContext("webgl"),f=a.width,k=a.height,e=d(g,"precision lowp float;                  \n                    \n                    // IN Vertex Position and\n                    // IN Texture Coordinates\n                    attribute vec2 a, b;\n                    \n                    // IN Vertex Color\n                    attribute vec4 c;\n\n                    // IN Light Value\n                    attribute vec3 _l;\n                    \n                    // OUT Texture Coordinates\n                    varying vec2 d;\n                    \n                    // OUT Vertex Color\n                    varying vec4 e;\n                    \n                    // OUT Light Value\n                    varying vec3 l;\n                    \n                    // CONST View Matrix\n                    uniform mat4 m;\n                    uniform vec2 r;\n                    \n                    void main(){\n                        gl_Position\x3dm*vec4(a,1.0,1.0);\n                        d\x3db;\n                        e\x3dc;\n                        l\x3d_l;\n                    }",
"precision lowp float;\n                        // OUT Texture Coordinates\n                        varying vec2 d;\n                        \n                        // OUT Vertex Color\n                        varying vec4 e;\n                        \n                        // OUT Light Strength\n                        varying vec3 l;\n                        \n                        // CONST Single Sampler2D\n                        uniform sampler2D f;\n\n                        void main(){\n                            gl_FragColor\x3dtexture2D(f,d)*e;\n                            gl_FragColor.rgb*\x3dl;\n                        }"),
w=g.bufferSubData.bind(g),H=g.drawElements.bind(g),B=g.bindTexture.bind(g),K=g.clear.bind(g),E=g.clearColor.bind(g),I=new ArrayBuffer(1398016),p=new Float32Array(I),L=new Uint32Array(I);var x=new Uint16Array(131064);var t=b(g,34963,x.byteLength,35044);var z=b(g,34962,I.byteLength,35048);var y=0,m=new Float32Array([1,0,0,1,0,0]),u=new Float32Array(100),q=0,U=Math.cos,V=Math.sin,O=null;g.blendFunc(770,771);g.enable(3042);g.useProgram(e);g.bindBuffer(34963,t);for(c=t=0;65532>t;t+=6,c+=4)x[t+0]=c,x[t+
1]=c+1,x[t+2]=c+2,x[t+3]=c+0,x[t+4]=c+3,x[t+5]=c+1;w(34963,0,x);g.bindBuffer(34962,z);x=g.getAttribLocation(e,"a");z=g.getAttribLocation(e,"b");t=g.getAttribLocation(e,"c");c=g.getAttribLocation(e,"_l");g.enableVertexAttribArray(x);g.vertexAttribPointer(x,2,5126,!1,32,0);g.enableVertexAttribArray(z);g.vertexAttribPointer(z,2,5126,!1,32,8);g.enableVertexAttribArray(t);g.vertexAttribPointer(t,4,5121,!0,32,16);g.uniformMatrix4fv(g.getUniformLocation(e,"m"),!1,new Float32Array([2/f,0,0,0,0,-2/k,0,0,0,
0,1,1,-1,1,0,0]));g.enableVertexAttribArray(c);g.vertexAttribPointer(c,3,5126,!1,32,20);g.activeTexture(33984);let S={gl:g,canvas:a,col:4294967295,bkg:function(b,a,c){E(b,a,c,1)},cls:function(){K(16384)},trans:function(b,a){m[4]=m[0]*b+m[2]*a+m[4];m[5]=m[1]*b+m[3]*a+m[5]},scale:function(b,a){m[0]*=b;m[1]*=b;m[2]*=a;m[3]*=a},rot:function(b){var a=m[0],c=m[1],d=m[2],h=m[3],f=V(b);b=U(b);m[0]=a*b+d*f;m[1]=c*b+h*f;m[2]=a*-f+d*b;m[3]=c*-f+h*b},push:function(){u[q+0]=m[0];u[q+1]=m[1];u[q+2]=m[2];u[q+3]=
m[3];u[q+4]=m[4];u[q+5]=m[5];q+=6},pop:function(){q-=6;m[0]=u[q+0];m[1]=u[q+1];m[2]=u[q+2];m[3]=u[q+3];m[4]=u[q+4];m[5]=u[q+5]},img:function(b,a,c,d,h,f,k,g,e,n={x:1,y:1,z:1}){var v=a+d,K=c+h;h=c+h;d=a+d;var E=m[0],q=m[1],t=m[2],u=m[3],x=m[4],z=m[5],M=S.col;(b!=O||10922<=y+1)&&(w(34962,0,I),H(4,6*y,5123,0),y=0,O!=b&&B(3553,O=b));b=32*y;p[b++]=a*E+c*t+x;p[b++]=a*q+c*u+z;p[b++]=f;p[b++]=k;L[b++]=M;p[b++]=n.x;p[b++]=n.y;p[b++]=n.z;p[b++]=v*E+K*t+x;p[b++]=v*q+K*u+z;p[b++]=g;p[b++]=e;L[b++]=M;p[b++]=n.x;
p[b++]=n.y;p[b++]=n.z;p[b++]=a*E+h*t+x;p[b++]=a*q+h*u+z;p[b++]=f;p[b++]=e;L[b++]=M;p[b++]=n.x;p[b++]=n.y;p[b++]=n.z;p[b++]=d*E+c*t+x;p[b++]=d*q+c*u+z;p[b++]=g;p[b++]=k;L[b++]=M;p[b++]=n.x;p[b++]=n.y;p[b++]=n.z;10922<=++y&&(w(34962,0,I),H(4,6*y,5123,0),y=0)},flush:function(){0!=y&&(w(34962,0,p.subarray(0,32*y)),H(4,6*y,5123,0),y=0)}};return S}}(a.GL||(a.GL={}))}(G||(G={}));
(function(a){!function(c){c.TextureAtlasStore={};c.TextureStore={};c.load=function(e,d){let b=0,k=()=>{0>=--b&&d()};for(let d in e){let f=new Image;var h=e[d];f.onload="sWidth"in h&&"sHeight"in h?function(b,d,h){let f=e[b];return()=>{let k=a.GL.CreateTexture(a.Core._gl.gl,d,d.width,d.height),g=f.textures;c.TextureAtlasStore[b]=k;for(let b=0;b<g.length;b++)for(let a=0;a<g[b].length;a++)c.TextureStore[g[b][a]]={atlas:k,w:f.sWidth,h:f.sHeight,u0:a*f.sWidth/d.width,v0:b*f.sHeight/d.height,u1:(a*f.sWidth+
f.sWidth)/d.width,v1:(b*f.sHeight+f.sHeight)/d.height};h()}}(d,f,k):function(b,d,h){let f=e[b];return()=>{let k=a.GL.CreateTexture(a.Core._gl.gl,d,d.width,d.height),g=f.textures;c.TextureAtlasStore[b]=k;for(let b of g)c.TextureStore[b.name]={atlas:k,w:b.width,h:b.height,u0:b.x/d.width,v0:b.y/d.height,u1:(b.x+b.width)/d.width,v1:(b.y+b.height)/d.height};h()}}(d,f,k);b++;f.src=e[d].loc}}}(a.Assets||(a.Assets={}))})(G||(G={}));
(function(a){!function(c){function e(b,a,c,d){let f=[];var h=Math.abs(c-b),k=Math.abs(d-a),g=b,e=a,B=1+h+k;b=b<c?1:-1;a=a<d?1:-1;d=h-k;h*=2;for(k*=2;0<B;)f.push({x:g,y:e}),0<d?(g+=b,d-=k):(e+=a,d+=h),--B;return f}function d(b,a,c){let d=[],f=0,h=~~(1-c);for(;f<=c;)d.push({x:c+b,y:f+a}),d.push({x:f+b,y:c+a}),d.push({x:-c+b,y:f+a}),d.push({x:-f+b,y:c+a}),d.push({x:-c+b,y:-f+a}),d.push({x:-f+b,y:-c+a}),d.push({x:c+b,y:-f+a}),d.push({x:f+b,y:-c+a}),f+=1,h+=0>=h?2*f+1:2*(f- --c)+1;return d}c.calculateLight=
function(b,c){b.a=[];let h=d(b.position.x,b.position.y,b.radius);for(let d in h){let f=e(b.position.x,b.position.y,h[d].x,h[d].y),k=b.intensity/f.length,g=0;for(let d in f){if(0>f[d].x||f[d].x>=c.mapSize.x||0>f[d].y||f[d].y>=c.mapSize.y)break;let h=f[d].y*c.mapSize.x+f[d].x,e=k*(f.length-parseInt(d)),n=a.TileMap.getTile(c,{x:f[d].x,y:f[d].y});if(n.hasCollision&&0<g)break;if(h in b.a&&!(b.a[h]>e)||(b.a[h]=1<e?1:e),n.hasCollision)break;if(n.hasCollision&&1<g)break;if(n.hasCollision&&g++,!n)break}}};
c.calculateLightMap=function(b){let a=[];for(let d in b)for(let c in b[d].a)(!a[c]||a[c]>b[d].a[c])&&(a[c]=b[d].a[c]);return a};c.pointsOnLine=e;c.pointsOnCircle=d}(a.Lighting||(a.Lighting={}))})(G||(G={}));
(function(a){a.TileStorage={};a.TileNames={};(function(c){let e;!function(a){a.draw=function(b,a,d,e,f){c.Texture.draw({renderer:b,texture:d,position:{x:e*d.w-a.position.x,y:f*d.h-a.position.y}})}}(e=c.Tile||(c.Tile={}));(function(d){d.draw=function(b,d,c){let h=C(d.position,c.tileSize),f=C(d.size,c.tileSize);for(let k=h.x;k<=h.x+f.x;k++)for(let g=h.y;g<=h.y+f.y;g++){let f=a.TileMap.getTile(c,{x:k,y:g});null!=f&&(b.col=f.colour,e.draw(b,d,f.texture,k,g))}}})(c.TileMap||(c.TileMap={}))})(a.Graphics||
(a.Graphics={}));(function(c){function e(){return d.next().value}let d=function*(){let b=0;for(;;)yield b++}();c.NextTileId=e;c.CreateAndStore=function(b,d,c,g){d={id:e(),texture:d,colour:c,hasCollision:g};return a.TileStorage[b]=d,a.TileNames[d.id]=b,d}})(a.Tile||(a.Tile={}));(function(c){c.addTile=function(a,d,b){b=b.x+b.y*a.mapSize.x;void 0===a.tiles[b]&&(a.tiles[b]=0);a.tiles[b]|=d.hasCollision?1:0;a.tiles[b]|=d.id<<1};c.getTile=function(c,d){return d.x>=c.mapSize.x||d.y>=c.mapSize.y||0>d.x||
0>d.y?null:a.TileStorage[a.TileNames[c.tiles[d.x+d.y*c.mapSize.x]>>1]]}})(a.TileMap||(a.TileMap={}))})(G||(G={}));
(function(a){!function(a){function c(a,b){b=a.interpolator.next(b);let c=a.origin,d=a.target;a.position.x=c.x+Math.round((d.x-c.x)*b.value);a.position.y=c.y+Math.round((d.y-c.y)*b.value);1==b.done&&(a.moving=!1,a.position=r(a.target),a.origin=r(a.target),a.interpolator=null)}a.create=function(a,b){return{position:a,origin:a,target:a,size:b,moving:!1,interpolator:null}};a.update=function(a,b){a.moving&&c(a,b)};a.move=function(a,b,c,h=0,e=(b)=>b){a.target=r(b);a.origin=r(a.position);a.interpolator=
N(c,h,e);a.moving=!0};a.interpolate=c}(a.Camera||(a.Camera={}))})(G||(G={}));
(function(a){!function(c){c.SpriteStore={};c.NinePatchStore={};class e{constructor(b){this.animations={};this.animationQueue=[];this.animations.DEFAULT=b;this.play("DEFAULT")}clone(){let b=new e(this.animations.DEFAULT.clone());for(let a in this.animations)b.addAnimation(a,this.animations[a].clone());return b}get currentAnimation(){return this.animationQueue[0]}get currentFrame(){return this.currentAnimation.currentFrame}addAnimation(b,a){this.animations[b]=a}play(b,a=!1){this.animationQueue.length=
0;b=this.animations[b].clone();return b.loop=a,this.animationQueue.push(b),this}then(b,a=!1){b=this.animations[b].clone();return b.loop=a,this.animationQueue.push(b),this}next(){this.animationQueue.shift();0===this.animationQueue.length&&this.stop()}stop(){this.animationQueue.length=0;this.animationQueue.push(this.animations.DEFAULT)}update(b,a){this.currentAnimation.done&&this.next();this.currentAnimation.update(a)}}let d;c.Sprite=e;(function(b){class d{constructor(b){this._duration=-1;this.progress=
0;this.done=this.loop=!1;this.frames=b}get currentFrame(){if(0===this.duration)return this.frames[0];{let b=0;for(let a in this.frames)if(b+=this.frames[a].duration,this.progress<=b)return this.frames[a];return this.frames[this.frames.length-1]}}get duration(){if(-1===this._duration){this._duration=0;for(let b of this.frames)this._duration+=b.duration}return this._duration}clone(){return new d(this.frames)}update(b){if(this.done=!1,0===this.duration)return this.frames[0];this.progress+=b;this.progress>
this.duration&&(this.loop?this.progress=0:(this.progress=0,this.done=!0))}}b.Animation=d;b.CreateAndStore=function(d){let h=new b(new b.Animation([{texture:a.Assets.TextureStore[d.animations.DEFAULT[0].texture],duration:d.animations.DEFAULT[0].duration}]));for(let c in d.animations){let f=d.animations[c],e=[];for(let b of f)e.push({texture:a.Assets.TextureStore[b.texture],duration:b.duration});h.addAnimation(c,new b.Animation(e))}return c.SpriteStore[d.name]=h,h}})(e=c.Sprite||(c.Sprite={}));(function(b){b.draw=
function(b,a,c,f,e,v){e=c+e-1;let h=f+v-1;for(let g=c;g<=e;g++)for(let k=f;k<=h;k++)v=g===c?k===f?a.tl:k===h?a.bl:a.ml:g===e?k===f?a.tr:k===h?a.br:a.mr:k===f?a.tc:k===h?a.bc:a.mc,d.draw({renderer:b,texture:v,position:{x:g*v.w,y:k*v.h}})}})(c.NinePatch||(c.NinePatch={}));(function(b){b.draw=function(b){let a=b.texture,c=a.w,d=~~(c/2),e=a.h,k=~~(e/2),w=b.renderer,H=b.light?b.light:{x:1,y:1,z:1},B=b.position;w.push();w.trans(B.x+d,B.y+k);b.scale&&w.scale(b.scale.x,b.scale.y);b.rotation&&w.rot(b.rotation);
w.img(a.atlas,-d,-k,c,e,a.u0,a.v0,a.u1,a.v1,H);w.pop()}})(d=c.Texture||(c.Texture={}));(function(b){let c;!function(b){b[b.LEFT=0]="LEFT";b[b.CENTER=1]="CENTER";b[b.RIGHT=2]="RIGHT"}(c=b.Alignment||(b.Alignment={}));b.draw=function(b,d,f,e,k=c.LEFT,w=0){let h=d.split(" "),g=f,n=0;f=0==w?6*d.split("").length:w;d=0;k==c.CENTER?d=~~(-f/2):k===c.RIGHT&&(d=~~-f);for(let c of h){0!=w&&n+6*c.length>w&&(e+=6,n=0);for(let h of c.split(""))f=h.toLowerCase(),k=a.Assets.TextureStore[f],f=g+n,b.push(),b.trans(f,
e),b.img(k.atlas,d,0,k.w,k.h,k.u0,k.v0,k.u1,k.v1),b.pop(),n+=6;n+=6}}})(c.Text||(c.Text={}))}(a.Graphics||(a.Graphics={}))})(G||(G={}));
(function(a){!function(a){function c(a){g||(a=a.which,h[a]&&b[a]&&b[a].keyDown(),h[a]=!1,k[a]=!0)}function d(a){g||(a=a.which,b[a]&&b[a].keyUp(),k[a]=!1,h[a]=!0)}a.Controls={};let b=[],k=[],h=[],g=!1;for(let a=0;256>a;a++)h[a]=!0;window.onkeydown=c;window.onkeyup=d;a.keyDown=c;a.keyUp=d;a.disable=function(){g=!0;k.forEach((a,c,d)=>{a&&b[c].keyUp();d[c]=!1});h.forEach((a,b,c)=>{c[b]=!0})};a.enable=function(){g=!1};a.bindKey=function(a,c,d=()=>{}){b[a]={keyDown:c,keyUp:d}};a.unbindKey=function(a){delete b[a]};
a.unbindAll=function(){for(let a in b)delete b[a]};a.bindControl=function(c,d,e=()=>{}){for(let f of a.Controls[c])b[f]={keyDown:d,keyUp:e}};a.unbindControl=function(c){for(let d of a.Controls[c])delete b[d]}}(a.Input||(a.Input={}))})(G||(G={}));
(function(a){a.Scene=class{constructor(a){this._storage={};this.transitionIn=a.transitionIn;this.transitionOut=()=>{this._storage={};a.transitionOut()};this.update=a.update;this.render=a.render;this.name=a.name}attach(a,e){return this._storage[a]=e,e}fetch(a){return this._storage[a]}};(function(c){function e(d){if(f){let f=d-k;k=d;g||function(a,c){let d=b.current;d&&d.update(a,c)}(d,f);(function(d,e){let f=b.current;(c._gl.cls(),g)?(d=~~(c.WIDTH/2),e=~~(c.HEIGHT/2),c._gl.col=4294967295,a.Graphics.Text.draw(c._gl,
"game paused",d,e-8,a.Graphics.Text.Alignment.CENTER),a.Graphics.Text.draw(c._gl,"click here to resume",d,e+8,a.Graphics.Text.Alignment.CENTER)):f&&f.render(c._gl,d,e);c._gl.flush()})(d,f);requestAnimationFrame(e)}}let d,b,k,h;c.WIDTH=0;c.HEIGHT=0;c.addScene=function(a){b.register(a)};c.pushScene=function(a,...d){b.push(a,...d)};c.popScene=function(){b.pop()};let g=!1,f=!1;c.init=function(e){d=e;c._gl=a.GL.Renderer(d);b=new a.StateMachine;c.WIDTH=c._gl.canvas.width;c.HEIGHT=c._gl.canvas.height};c.start=
function(){k=performance.now();c._gl.bkg(0,0,0);f=!0;h=requestAnimationFrame(e)};c.stop=function(){f=!1;cancelAnimationFrame(h)};c.pause=function(){g=!0;a.Input.disable()};c.unpause=function(){g=!1;a.Input.enable()}})(a.Core||(a.Core={}))})(G||(G={}));
(function(a){var c=null;a.setStorage=function(a){c=a};a.newGame=function(){T.gameState={version:"0.0.0"}};a.save=function(){c.setItem("save",JSON.stringify(T.gameState))};a.saveExists=function(){var a=c.getItem("save");return null!=a&&""!=a};a.load=function(){var a=c.getItem("save");T.gameState=JSON.parse(a)}})(P||(P={}));
(function(a){var c=G,e=c.Core,d=c.Input,b=c.Graphics,k=c.Assets;let h,g=0;a.TitleMenu=new c.Scene({name:"TitleMenu",transitionIn(){h=P.saveExists()?["Continue","New Game","Settings"]:["New Game","Settings"];d.bindControl("DOWN",()=>{(g+=1)>h.length-1&&(g=0)});d.bindControl("UP",()=>{0>--g&&(g=h.length-1)});d.bindControl("ACTION",()=>{switch(h[g]){case "Continue":P.load();e.pushScene("Game");break;case "New Game":P.newGame();e.pushScene("Game");break;case "Settings":e.pushScene("SettingsMenu")}})},
transitionOut(){d.unbindControl("DOWN");d.unbindControl("UP");d.unbindControl("ACTION")},update(){},render(a){a.col=4294901760;b.NinePatch.draw(a,b.NinePatchStore.dialog,0,0,32,18);a.col=4294967295;e.WIDTH;let d=~~(e.HEIGHT/2);b.Text.draw(a,"Tower Defense",16,16,b.Text.Alignment.LEFT);h.forEach((c,e)=>{b.Text.draw(a,c,32,d+16*e,b.Text.Alignment.LEFT)});b.Texture.draw({renderer:a,texture:k.TextureStore.cursor,position:{x:16,y:d-2+16*g}})}})})(R||(R={}));
(function(a){!function(a){!function(a){a.Position=class{constructor(a,d,c=!0){this.name=a;this.value=d;this.active=c}};a.Tag=class{constructor(a){this.value=this.name=a}};a.Flag=class{constructor(a,d){this.name=a;this.value=d}};a.Number=class{constructor(a,d){this.name=a;this.value=d}};a.Object=class{constructor(a,d){this.name=a;this.value=d}};a.coalesceValue=function(a,d){return null!=a?a.value:d}}(a.Component||(a.Component={}));class c{constructor(a){this._components={};this.id=c.__id++;this._manager=
a||null}SetManager(a){null!=this._manager&&this.DetachManager();this._manager=a;for(let a in this._components)this.registerComponentWithManager(this._components[a])}DetachManager(){for(let a in this._manager.collections){let b=this._manager.collections[a].indexOf(this);-1!==b&&this._manager.collections[a].splice(b,1)}this._manager=null}registerComponentWithManager(a){null==this._manager.collections[a.name]&&(this._manager.collections[a.name]=[]);this._manager.collections[a.name].push(this);this._manager.emit(this,
a.name,"added")}addComponent(a){return this._components[a.name]=a,null!=this._manager&&this.registerComponentWithManager(a),a}getComponent(a){return null==this._components[a]?null:this._components[a]}hasComponent(a){return null!=this._components[a]}}c.__id=0;a.Entity=c;a.Manager=class{constructor(){this.collections={};this._eventHandlers={};this.entities=[]}addEntity(a){return null==a?a=new c(this):a.SetManager(this),this.entities.push(a),a}getAll(a){return this.collections[a]}getFirst(a){return null==
this.collections[a]?null:this.collections[a][0]}on(a,b,c){null==this._eventHandlers[a]&&(this._eventHandlers[a]={});null==this._eventHandlers[a][b]&&(this._eventHandlers[a][b]=[]);this._eventHandlers[a][b].push(c)}emit(a,b,c){this._eventHandlers[b]&&this._eventHandlers[b][c]&&this._eventHandlers[b][c].forEach((d)=>{d(a,this.collections[b],c)})}}}(a.ECS||(a.ECS={}))})(G||(G={}));
(function(a){a.handlePlayerInput=function(a){let c=a.getComponent("tilePos"),b=a.getComponent("targetTile"),e=a.getComponent("moving"),h=a.getComponent("movingRight"),g=a.getComponent("movingLeft"),f=a.getComponent("movingUp");a=a.getComponent("movingDown");0==e.value&&(h.value&&b.value.x++,g.value&&b.value.x--,f.value&&b.value.y--,a.value&&b.value.y++,c.value.x==b.value.x&&c.value.y==b.value.y||(e.value=!0))};a.handleCollision=function(a,c){let b=a.getComponent("tilePos"),d=a.getComponent("targetTile"),
e=a.getComponent("moving"),g=a.getComponent("movingRight"),f=a.getComponent("movingLeft"),n=a.getComponent("movingUp");a=a.getComponent("movingDown");if(g.value||f.value){let a=G.TileMap.getTile(c,{x:d.value.x,y:b.value.y});a&&a.hasCollision&&(g.value=f.value=!1,d.value.x=b.value.x)}(n.value||a.value)&&(c=G.TileMap.getTile(c,{x:b.value.x,y:d.value.y}))&&c.hasCollision&&(n.value=a.value=!1,d.value.y=b.value.y);b.value.x===d.value.x&&b.value.y===d.value.y&&(e.value=!1)};let c={};a.moveEntity=function(a,
d){let b=a.getComponent("tilePos"),e=a.getComponent("targetTile"),h=a.getComponent("renderPos"),g=a.getComponent("moving");null==c[a.id]&&(c[a.id]={});null==c[a.id].moveFn&&(c[a.id].moveFn=N(d,200,J.linear));d=c[a.id].moveFn.next(d);let f=A(b.value,8),n=A(e.value,8);h.value.x=f.x+Math.round((n.x-f.x)*d.value);h.value.y=f.y+Math.round((n.y-f.y)*d.value);1==d.done&&(g.value=!1,b.value=r(e.value),h.value=A(b.value,8),delete c[a.id].moveFn)}})(Q||(Q={}));
(function(a){!function(a){!function(a){var c=G.Input;a.Move=new G.Scene({name:"Move",transitionIn(a){this.attach("parentScene",a);let b=a.fetch("ecsManager").getFirst("player");c.bindControl("RIGHT",()=>{b.getComponent("movingRight").value=!0},()=>{b.getComponent("movingRight").value=!1});c.bindControl("LEFT",()=>{b.getComponent("movingLeft").value=!0},()=>{b.getComponent("movingLeft").value=!1});c.bindControl("DOWN",()=>{b.getComponent("movingDown").value=!0},()=>{b.getComponent("movingDown").value=
!1});c.bindControl("UP",()=>{b.getComponent("movingUp").value=!0},()=>{b.getComponent("movingUp").value=!1})},transitionOut(){c.unbindAll()},update(){},render(){}})}(a.SubScenes||(a.SubScenes={}))}(a.Game||(a.Game={}))})(R||(R={}));(function(a){!function(a){!function(a){a.Build=new G.Scene({name:"Build",transitionIn(a){this.attach("parentScene",a)},transitionOut(){},update(){},render(){}})}(a.SubScenes||(a.SubScenes={}))}(a.Game||(a.Game={}))})(R||(R={}));
(function(a){!function(a){!function(a){a.Defend=new G.Scene({name:"Defend",transitionIn(a){this.attach("parentScene",a)},transitionOut(){},update(){},render(){}})}(a.SubScenes||(a.SubScenes={}))}(a.Game||(a.Game={}))})(R||(R={}));
(function(a){!function(a){var c=G,d=c.ECS,b=d.Component,k=c.Graphics;a.scene=new c.Scene({name:"Game",transitionIn(){this.attach("cameraGap",48);this.attach("camera",G.Camera.create({x:0,y:0},{x:192,y:144}));var c=this.attach("ecsManager",new d.Manager);c.on("renderable","added",(a,b)=>{b.sort((a,b)=>d.Component.coalesceValue(a.getComponent("sort"),0)-d.Component.coalesceValue(b.getComponent("sort"),0))});let g={mapSize:{x:32,y:16},tileSize:8,tiles:[]};!function(a){for(let b=0;b<a.mapSize.x;b++)for(let c=
0;c<a.mapSize.y;c++)b===a.mapSize.x-1||0===b||c===a.mapSize.y-1?G.TileMap.addTile(a,G.TileStorage.wall,{x:b,y:c}):0===c?G.TileMap.addTile(a,G.TileStorage.north_wall,{x:b,y:c}):G.TileMap.addTile(a,G.TileStorage.floor,{x:b,y:c})}(g);var f=c.addEntity();f.addComponent(new b.Tag("renderable"));f.addComponent(new b.Tag("levelMap"));f.addComponent(new b.Object("tileMap",g));f.addComponent(new b.Number("sort",1));f=c.addEntity();f.addComponent(new b.Tag("player"));f.addComponent(new b.Tag("renderable"));
var e=f.addComponent(new b.Position("tilePos",{x:1,y:1}));f.addComponent(new b.Position("renderPos",A(e.value,g.tileSize)));f.addComponent(new b.Position("targetTile",r(e.value)));f.addComponent(new b.Flag("moving",!1));f.addComponent(new b.Flag("movingLeft",!1));f.addComponent(new b.Flag("movingRight",!1));f.addComponent(new b.Flag("movingUp",!1));f.addComponent(new b.Flag("movingDown",!1));e=k.SpriteStore.cursor.clone();e.play("blink",!0);f.addComponent(new b.Object("sprite",e));f.addComponent(new b.Number("sort",
2));f.addComponent(new b.Number("colour",4294910498));for(f=0;10>f;f++){e=c.addEntity();e.addComponent(new b.Tag("renderable"));var v=e.addComponent(new b.Position("tilePos",{x:-2,y:f+1}));e.addComponent(new b.Position("renderPos",A(v.value,g.tileSize)));v=k.SpriteStore.cursor.clone();0==f%2?v.play("blink",!0):v.play("quick-blink",!0);e.addComponent(new b.Object("sprite",v));e.addComponent(new b.Number("sort",3));v=F(D(50,255),D(50,255),D(50,255),D(175,255));e.addComponent(new b.Number("colour",v))}c=
c.addEntity();c.addComponent(new b.Number("sort",-10));c.addComponent(new b.Tag("renderable"));c=this.attach("subSceneManager",new G.StateMachine);c.register(a.SubScenes.Move);c.register(a.SubScenes.Build);c.register(a.SubScenes.Defend);c.push("Move",this)},transitionOut(){},update(a,b){var c=this.fetch("ecsManager"),d=c.getFirst("player"),e=c.getFirst("levelMap").getComponent("tileMap").value;let g=this.fetch("camera"),h=this.fetch("cameraGap");Q.handlePlayerInput(d);c.getAll("sprite").forEach((c)=>
{c.getComponent("sprite").value.update(a,b)});c=d.getComponent("moving");(c.value&&(Q.handleCollision(d,e),c.value&&Q.moveEntity(d,a)),g.moving)||(d=d.getComponent("renderPos").value,e=d.x-(g.position.x+~~(g.size.x/2)),c=d.y-(g.position.y+~~(g.size.y/2)),(e>=h||e<=-h||c>=h||c<=-h)&&G.Camera.move(g,{x:d.x-~~(g.size.x/2),y:d.y-~~(g.size.y/2)},a,1500,J.outQuart));G.Camera.update(g,a)},render(a){let c=this.fetch("ecsManager"),d=this.fetch("camera");a.bkg(0,0,0);c.getAll("renderable").forEach((c)=>{if(c.hasComponent("tileMap"))c=
c.getComponent("tileMap").value,k.TileMap.draw(a,d,c);else if(c.hasComponent("sprite")){let f=c.getComponent("sprite").value,e=c.getComponent("renderPos").value;a.col=b.coalesceValue(c.getComponent("colour"),4294967295);k.Texture.draw({renderer:a,texture:f.currentFrame.texture,position:l.sub(e,d.position)})}});a.col=4294936712;k.NinePatch.draw(a,k.NinePatchStore.dialog,24,0,8,18)}})}(a.Game||(a.Game={}))})(R||(R={}));
(function(a){var c=G,e=c.Core,d=c.Input,b=c.Graphics,k=c.Assets;let h,g=0;a.SettingsMenu=new c.Scene({name:"SettingsMenu",transitionIn(){h=["Back"];d.bindControl("DOWN",()=>{(g+=1)>h.length-1&&(g=0)});d.bindControl("UP",()=>{0>--g&&(g=h.length-1)});d.bindControl("ACTION",()=>{switch(h[g]){case "Back":e.popScene()}})},transitionOut(){d.unbindControl("DOWN");d.unbindControl("UP");d.unbindControl("ACTION")},update(){},render(a){a.col=4278190335;b.NinePatch.draw(a,b.NinePatchStore.dialog,0,0,32,18);a.col=
4294967295;let c=~~(e.WIDTH/2),d=~~(e.HEIGHT/2);h.forEach((e,f)=>{b.Text.draw(a,e,c-16,d+16*f,b.Text.Alignment.LEFT)});b.Texture.draw({renderer:a,texture:k.TextureStore.cursor,position:{x:c-32,y:d-2+16*g}})}})})(R||(R={}));
(function(a){var c=G,e=c.Core,d=c.Input,b=c.Graphics;a.PostGame=new c.Scene({name:"PostGame",transitionIn(){d.bindControl("ACTION",()=>{e.popScene();e.popScene()})},transitionOut(){d.unbindControl("ACTION")},update(){},render(a){a.col=4292682274;b.NinePatch.draw(a,b.NinePatchStore.dialog,0,0,32,18);a.col=4294967295;b.Text.draw(a,"Winner is you.",~~(e.WIDTH/2),~~(e.HEIGHT/2),b.Text.Alignment.CENTER)}})})(R||(R={}));
(function(a){var c=G.Core,e=G.Graphics,d=G.Assets;let b=[{name:"cursor",animations:{DEFAULT:[{texture:"cursor",duration:0}],blink:[{texture:"cursor_light",duration:250},{texture:"cursor",duration:250},{texture:"cursor_dark",duration:250},{texture:"cursor",duration:250}],"quick-blink":[{texture:"cursor_light",duration:150},{texture:"cursor",duration:150},{texture:"cursor_dark",duration:150},{texture:"cursor",duration:150}]}}];a.gameState=null;a.setup=function(){c.addScene(R.TitleMenu);c.addScene(R.SettingsMenu);
c.addScene(R.Game.scene);c.addScene(R.PostGame);for(let a of b)e.Sprite.CreateAndStore(a);G.Tile.CreateAndStore("north_wall",d.TextureStore.brick,4294928247,!0);G.Tile.CreateAndStore("wall",d.TextureStore.brick,4294928247,!0);G.Tile.CreateAndStore("floor",d.TextureStore.brick,4281150765,!1);e.NinePatchStore.dialog={tl:d.TextureStore.dialog_tl,tc:d.TextureStore.dialog_t,tr:d.TextureStore.dialog_tr,ml:d.TextureStore.dialog_ml,mc:d.TextureStore.dialog_m,mr:d.TextureStore.dialog_mr,bl:d.TextureStore.dialog_bl,
bc:d.TextureStore.dialog_b,br:d.TextureStore.dialog_br};c.pushScene("TitleMenu")}})(T||(T={}));
(function(a){var c=G.Core,e=G.Input,d=G.Assets;let b={alpha:{loc:"res/alpha.png",sWidth:5,sHeight:5,textures:["abcdefghijklmnopqrstuvwxyz".split(""),"1234567890.!?#()-^+\x3d/\\:,'\"".split("")]},tiles:{loc:"res/test.png",sWidth:8,sHeight:8,textures:[["brick","cursor","cursor_dark","cursor_light"],["dialog_tl","dialog_t","dialog_tr","blank03"],["dialog_ml","dialog_m","dialog_mr","blank04"],["dialog_bl","dialog_b","dialog_br","blank05"]]},irreg:{loc:"res/irreg.png",textures:[{name:"test",x:0,y:0,width:32,
height:32}]}};a.onload=function(){function k(){var a=c._gl.canvas,b=0|Math.min(window.innerWidth/a.width,window.innerHeight/a.height);b=0>=b?1:b;a=[a.width*b,a.height*b];a=[(window.innerWidth-a[0])/2,(window.innerHeight-a[1])/2];b="translate("+~~a[0]+"px, "+~~a[1]+"px) scale("+~~b+")";a=document.getElementById("stage");a.style.transform=b;a.style.webkitTransform=b}c.init(document.getElementById("canvas"));P.setStorage(window.localStorage);e.Controls.UP=[38,87];e.Controls.DOWN=[40,83];e.Controls.LEFT=
[37,65];e.Controls.RIGHT=[39,68];e.Controls.ACTION=[13,32];d.load(b,()=>{window.onresize=k;k();window.onblur=()=>{c.pause()};window.onfocus=()=>{c.unpause()};c.start();a.setup()})}})(T||(T={}));window.onload=T.onload;
})()